### ISSUE TITLE
save image

### ISSUE THREAD

**Issue by ascoders** [ascoders/react-native-image-viewer#1]
![111](https://cloud.githubusercontent.com/assets/7970947/18501090/878ad6f2-7a80-11e6-8602-a2c4d1f697f3.gif)
![222](https://cloud.githubusercontent.com/assets/7970947/18501091/87b14d8c-7a80-11e6-904d-8c434e1904ce.gif)
![333](https://cloud.githubusercontent.com/assets/7970947/18501092/87d5efe8-7a80-11e6-9234-516b2be1e729.gif)
![image](https://cloud.githubusercontent.com/assets/7970947/18501167/1d1adcf8-7a81-11e6-8551-163634b3bedd.png)

**Comment by ascoders** [comment]
![image](https://cloud.githubusercontent.com/assets/7970947/18501378/8830292a-7a82-11e6-9994-8c31ae0e6883.png)

**Comment by xiaozhicheng** [comment]
for ios only???

**Comment by ascoders** [comment]
![image](https://cloud.githubusercontent.com/assets/7970947/18977528/ac0710d0-86ed-11e6-9ad9-49952ff6cba0.png)

@xiaozhicheng also for android.

**Comment by ascoders** [comment]
![image](https://cloud.githubusercontent.com/assets/7970947/19636837/46d68bd6-99fe-11e6-8cb5-ce279dddd9c2.png)

**Comment by ascoders** [comment]
![image-viewer-drag](https://cloud.githubusercontent.com/assets/7970947/21086300/388dedfc-c056-11e6-955e-0a2a0b541f7f.gif)
![image-viewer-scan](https://cloud.githubusercontent.com/assets/7970947/21086323/7355face-c056-11e6-8d68-384000d41d47.gif)

**Comment by ascoders** [comment]
![image](https://cloud.githubusercontent.com/assets/7970947/21376663/ea10baf6-c771-11e6-9570-af3333428343.png)
