### ISSUE TITLE
如何实现双击放大呢？

### ISSUE THREAD

**Issue by luojf945** [ascoders/react-native-image-viewer#10]
就像微信朋友圈里面图片预览一样的效果，双击是图片放大

**Comment by ascoders** [comment]
这个功能还没有做，很需要的话我就加上呗

**Comment by xuanheScript** [comment]
@ascoders 那就麻烦加上吧 👍

**Comment by ascoders** [comment]
行，这周略忙，尽量下周一之前加上

**Comment by Poordeveloper** [comment]
能否麻烦再加个功能支持设置当前图片，比如有三张图片，能够选择设置第二章为当前图片，显示的时候，就直接显示第二章，往左滑到第一张，往右滑到第三张，就像标准的微信previewImage api那样。

**Comment by ascoders** [comment]
#15 似乎有同学正在加

**Comment by simman** [comment]
@ascoders , 我看你的另一个 [https://github.com/ascoders/react-native-image-zoom/blob/master/image-zoom/image-zoom.component.tsx#L106](https://github.com/ascoders/react-native-image-zoom/blob/master/image-zoom/image-zoom.component.tsx#L106) 有实现, 为啥注释掉了

**Comment by ascoders** [comment]
这块儿还没想好怎么实现比较方便，最近太忙啦

**Comment by aijason** [comment]
@ascoders 双击放大图片的效果怎么实现呢，现在想做

**Comment by dongodngtang** [comment]
我也在做双击放大，需要点技术支持。我看了你的代码有写但注释点了，我尝试了一下，没有成功。没找到思路

**Comment by ascoders** [comment]
技术人员期待挑战嘛，我把这块实现留着没有做，期待pr！

**Comment by folyred** [comment]
拖了大半年了，请尽快实现哦，另外我建议提供一个onLongPress接口，让使用者自己定义长按事件

**Comment by folyred** [comment]
其实不用完整实现，可以对外暴露一个设置缩放scale的接口，借助onDoubleClick事件，设置scale值即可。

**Comment by ascoders** [comment]
@folyred 感谢提醒，双击功能已经完成，见 `react-native-image-zoom-viewer@2.0.4`。

**Comment by folyred** [comment]
已经升级到新版，并实现，再次感谢分享

**Comment by aijason** [comment]
怎么使用

**Comment by ascoders** [comment]
@aijason 直接升级即可，不需要额外配置，默认额外支持了双击放大功能。

**Comment by aijason** [comment]
点击图片，是否显示全屏观看时，是控制Modal的visiable属性为true或false就可以是吗

**Comment by aijason** [comment]
{/**查看大图*/}
                {
                    this.state.isShowBigImg?
                        <Modal visible={true} transparent={true}>
                            <ImageViewer
                                imageUrls={this.BigImgUrl}
                                index={this.state.firstShowIndex}
                                //onDoubleClick
                                onClick={()=>{
                                    this.setState({isShowBigImg:false})
                                }}
                            />
                        </Modal>:null
                }
我是这么用的。

**Comment by aijason** [comment]
{/**查看大图*/}
                {
                    this.state.isShowBigImg?
                        <Modal visible={true} transparent={true}>
                            <ImageViewer
                                imageUrls={this.BigImgUrl}
                                index={this.state.firstShowIndex}
                                //onDoubleClick
                                onClick={()=>{
                                    this.setState({isShowBigImg:false})
                                }}
                            />
                        </Modal>:null
                }

**Comment by aijason** [comment]
<Modal visible={true} transparent={true}>
                <ImageViewer imageUrls={images}/>
            </Modal>

**Comment by aijason** [comment]
-  <Modal visible={true} transparent={true}>
-                 <ImageViewer imageUrls={images}/>
-             </Modal>

**Comment by aijason** [comment]
` <Modal visible={true} transparent={true}>
                <ImageViewer imageUrls={images}/>
            </Modal>`

**Comment by aijason** [comment]
@ascoders `{/**查看大图*/}
                {
                    this.state.isShowBigImg?
                        <Modal visible={true} transparent={true}>
                            <ImageViewer
                                imageUrls={this.BigImgUrl}
                                index={this.state.firstShowIndex}
                                //onDoubleClick
                                onClick={()=>{
                                    this.setState({isShowBigImg:false})
                                }}
                            />
                        </Modal>:null
                }`

**Comment by ascoders** [comment]
是的

**Comment by aijason** [comment]
`<Modal visible={this.state.isShowBigImg} transparent={true}>
                    <ImageViewer
                        imageUrls={this.BigImgUrl}
                        index={this.state.firstShowIndex}
                        onClick={()=>{
                            this.setState({isShowBigImg:false})
                        }}
                    />
                </Modal>`
我这样子处理的话，双击就没效果了，因为单击时会退出大图观看模式，要怎么处理，才能单击既能退出，双击又能放大呢？

**Comment by aijason** [comment]
@ascoders

**Comment by aijason** [comment]
还有一个问题就是 ，怎么处理虚拟键盘返回也能退出大图浏览的模式。

**Comment by ascoders** [comment]
@aijason 虚拟键盘通过外部控制，把visible设置为false，这个组件不关心虚拟键盘的。
本来就能单击退出呀，把onClick去掉试试呢

**Comment by aijason** [comment]
我把onClick去掉，单击不能退出，因为visiable的值还是true，还是大图模式。双击放大是有效果的。

**Comment by aijason** [comment]
如果我在单击onclick处理this.setState({isShowBigImg:false})设置visiable为false，双击就没效果，因为单击已经退出了。

**Comment by aijason** [comment]
@ascoders
