### ISSUE TITLE
发现三个BUG:1:图片尺寸问题 2:renderFooter问题 3:failImageSource问题

### ISSUE THREAD

**Issue by BennyTian** [ascoders/react-native-image-viewer#101]
1: 图片尺寸问题:
   假设你有多张图,但图的比例或者尺寸不一样,当你第一次从右往左滑的时候,没有问题,但当你从从左往右滑回来的时候,图片的尺寸变了,只能显示图片的局部

2: renderFooter:
  完全无效

3: failImageSource:
  failImageSource={{uri:'http://xxxxxx'}}  完全无效果,只能看到一丁点

感谢作者的无私奉献, 要是能再修复这几个问题 就完美了.  尤其是 问题1, 图片尺寸会变的问题 .  

RN: 0.48.0
image-zoom-viewer  :  2.0.11

**Comment by ascoders** [comment]
现在双11期间，很忙，见谅哈，结束了会看看的。
第一个问题是由于回退时不会重置缩放，这是有意而为，我觉得可以考虑开放一个参数来设定。

**Comment by tianweicc** [comment]
我也需要  往回滑动的时候 图片显示不完全

**Comment by tianweicc** [comment]
@BennyTian   老铁 你解决了么

**Comment by sofwu** [comment]
@BennyTian 老铁 你解决了么

**Comment by BennyTian** [comment]
@tianweicc    @sofwu 

换成了这个组件 react-native-gallery    https://github.com/ldn0x7dc/react-native-gallery

**Comment by fenglu09** [comment]
@ascoders 请问第一个问题解决了吗？

**Comment by fenglu09** [comment]
@ascoders  第一次从右往左滑的时候,没有问题,但当你从从左往右滑回来的时候,图片的尺寸变了,而且位置也变了。

**Comment by kokiy** [comment]
me too @BennyTian  you fixed It ?

**Comment by zhengyeye** [comment]
你好@ascoders ，第一个图片尺寸的问题解决了么？

**Comment by ascoders** [comment]
@zhengyeye 第一个问题是由于回退时不会重置缩放，微信也是如此。

**Comment by fenglu09** [comment]
@ascoders  第一个问题，为什么图片的位置和大小都变了呢？

**Comment by Feng-xp** [comment]
我也遇到了类似的问题，显示3张图图片，尺寸个不一样，没有操作过缩放，滑动第一张，加载第二张图片的时候，第一张的尺寸就会变成第二张的尺寸，滑动第二张，加载第三张的时候，第二张的尺寸变成第三张的尺寸，以此类推，经过排查，发现只有image这个组件在Native中显示尺寸确实是变了，其他都没问题，在RN代码中，每张图片传的width，height也都没问题，很奇怪。
RN版本：0.5.1
最后我的解决方案是，设置图片的style为绝对布局：
imageStyle: {
            position: 'absolute',
            top: 0,
            bottom: 0,
            left: 0,
            right: 0,
        }

**Comment by giantliu22** [comment]
找到问题的地方了 image-viewer.component.tsx 文件中444行 改成 <Image style={Object.assign({},this.styles.imageStyle, { width.......  即可

**Comment by ascoders** [comment]
@giantliu22 很棒，应该就是这个问题，已经发布了 `2.0.14` 解决此问题。

如果还有其他问题，再 reopen 此 issue。

**Comment by tianweicc** [comment]
@ascoders 2.0.14 现在还搜不到 要多久才可以安装

**Comment by 369663841** [comment]
@giantliu22 @ascoders  感谢二位！

**Comment by ascoders** [comment]
@tianweicc 已经发布啦
