### ISSUE TITLE
图片放大后，点击安卓返回键，图片modal不可以关闭

### ISSUE THREAD

**Issue by zhoudanjun** [ascoders/react-native-image-viewer#104]
点击图片预览，进到大图预览，但是在安卓返回键里面，添加关闭图片预览modal事件没有用

附上代码
    onBackAndroid = () => {
      if(this.state.showImage){
        this._closeViewImage()；//关闭图片预览
      }else{
        this.props.navigation.goBack(null)
      }       
    };

**Comment by zhoudanjun** [comment]
`    onBackAndroid = () => {
      if(this.state.showImage){
        this._closeViewImage()；//关闭图片预览
      }else{
        this.props.navigation.goBack(null)
      }       
    };`

**Comment by ascoders** [comment]
```javascript
<Modal visible={true} transparent={true}>
  <ImageViewer imageUrls={images}/>
</Modal>
```

返回时，将 `visible` 设置为 `false`.
