### ISSUE TITLE
Giving error when loading image locally. How to load local image?

### ISSUE THREAD

**Issue by vijay-dadhich09** [ascoders/react-native-image-viewer#108]
Hi, I could not load local image, giving error. Can I load local image assets.
import IconSkywalk from '../../assets/icons/skywalk.png';
const images = [{ url: IconSkywalk }];
<ImageViewer
            imageUrls={images}
          />

but giving following error
image.url.startsWith is not a function in ImageViewer.loadImage

**Comment by ascoders** [comment]
```javascript
const images = [{
    url: 'data:image/png;base64,.....',
    width: 200,
    height: 200
}]
```

From #27
