### ISSUE TITLE
更新到最新版本以后，确实图片显示不出，android一直闪动

### ISSUE THREAD

**Issue by yuanji123** [ascoders/react-native-image-viewer#11]
1.2.24版本是可以显示出图片的，更新到1.2.25以后不行.  我更新1.2.25的原因是因为好像动态设置index以后，无法显示图片,

 <ImageViewer visible={true}
                        saveToLocalByLongPress={false}
                        onClick={this.backFullScreen}
                        loadingRender={() => {
                            return (
                                <TouchableOpacity
                                onPress = {this.backFullScreen}
                                >
                                    <View style={[styles.loading, { width: deviceWidth }]}>
                                        <ActivityIndicator
                                            size="large"
                                            color="#3e9ce9"
                                            />
                                        <Text style={styles.loadingText}>数据加载中...</Text>
                                    </View>
                                 </TouchableOpacity>
                            )
                        } }
                        imageUrls={this.state.images} />

一直出现进度条，没有出现图片

**Comment by ascoders** [comment]
恩，我看看

**Comment by hecomliufang49** [comment]
我也是这个错误，

**Comment by ascoders** [comment]
原因是安卓子元素变化也会不断触发 `onLayout`，迫使我没法好好动态计算宽高，不过现在通过 tag 解决了，升级到 `v1.2.26`

close #9
