### ISSUE TITLE
图片放大时modal的背景颜色能不能改掉，我去源码里面把所有黑色全部都换成白色了，但是不管用

### ISSUE THREAD

**Issue by jianjiandandan** [ascoders/react-native-image-viewer#110]
图片放大时modal的背景颜色能不能改掉，我去源码里面把所有黑色全部都换成白色了，但是不管用，作者能告诉我具体要改哪里么，或者把style这个方法给提供出来，我们可以自己去修改modal的背景色

**Comment by ascoders** [comment]
Modal 好像就是黑色的，改不了。

我在 Demo 里为了方便，放在 Modal 里，没有说你们用的时候也必须放在 Modal 里呀？

**Comment by 18059842153** [comment]
请问如何吧1/3 页数 删除获取隐藏

**Comment by ascoders** [comment]
@18059842153 重写 `renderIndicator `
