### ISSUE TITLE
typescript strictNullChecks crashes the lib

### ISSUE THREAD

**Issue by alexbuicescu** [ascoders/react-native-image-viewer#111]
When I try to run my app using strictNullChecks true, I get the following errors from this lib:

```log
ERROR in [at-loader] ./node_modules/react-native-image-pan-zoom/image-zoom/image-zoom.component.tsx:20:5 
    TS2322: Type 'null' is not assignable to type 'number'.

ERROR in [at-loader] ./node_modules/react-native-image-pan-zoom/image-zoom/image-zoom.component.tsx:25:5 
    TS2322: Type 'null' is not assignable to type 'number'.

ERROR in [at-loader] ./node_modules/react-native-image-pan-zoom/image-zoom/image-zoom.component.tsx:32:5 
    TS2322: Type 'null' is not assignable to type 'number'.

ERROR in [at-loader] ./node_modules/react-native-image-pan-zoom/image-zoom/image-zoom.component.tsx:86:17 
    TS2322: Type 'null' is not assignable to type 'number'.
...and so on
```

From my research I've found that [this issue](https://github.com/Microsoft/TypeScript/issues/15363) is very similar to this one, which suggests the packaging of the lib is wrong.

My tsconfig.json (```exclude``` is missing, because by default node_modules are excluded, so no need to add it):
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "allowJs": true,
    "experimentalDecorators": true,
    "jsx": "react",
    "module": "commonjs",
    "noImplicitAny": true,
    "outDir": "./dist/",
    "paths": {
      "src": [
        "."
      ]
    },
    "skipLibCheck": true,
    "sourceMap": true,
    "strictNullChecks": true,
    "target": "es6"
  },
  "include": [
    "./src/**/*"
  ]
}
```

As a temporary workaround I've copied the lib's auto generated js (from typescript) files to my project.

**Comment by ascoders** [comment]
fix in https://github.com/ascoders/react-native-image-zoom/commit/4d56eafef6ed8f3433c6b9ac2930100d9aaad1da. `2.0.9`

**Comment by alexbuicescu** [comment]
Great, when will it be published to npm? I tried ```npm install react-native-image-zoom-viewer@2.0.9``` and also the latest: ```npm install react-native-image-zoom-viewer@2.0.14``` and the error is still there.
