### ISSUE TITLE
Please release react-native-image-pan-zoom@^2.0.14 to npmjs

### ISSUE THREAD

**Issue by kala888** [ascoders/react-native-image-viewer#114]
![image](https://user-images.githubusercontent.com/1215976/33642046-0edd8ef8-da73-11e7-8163-164827dcb63f.png)

![image](https://user-images.githubusercontent.com/1215976/33642069-2d722f22-da73-11e7-9a3f-bb32f2bc2d96.png)

**Comment by ascoders** [comment]
I'm sorry, published `2.0.16` just now.
