### ISSUE TITLE
Android 上太卡

### ISSUE THREAD

**Issue by Feng-xp** [ascoders/react-native-image-viewer#116]
RT，滑不动，双击缩放很大几率不响应，直接消失了

**Comment by Feng-xp** [comment]
性能需要优化

**Comment by wlxscn** [comment]
有没有好用的类似组件

**Comment by AdamantG** [comment]
@wlxscn  Do you find some similar component ?

**Comment by ascoders** [comment]
在 IOS 没发现有性能问题，如果愿意帮助，可以根据 [开发指南](https://github.com/ascoders/react-native-image-viewer#development-pattern) 帮助我们一起找到性能问题。

**Comment by ascoders** [comment]
I fixed this performance problems in `2.0.19`
