### ISSUE TITLE
Android 上能不能支持 返回键 事件监听

### ISSUE THREAD

**Issue by uuau99999** [ascoders/react-native-image-viewer#118]
这个组件挺好用的，就是android 好像没有对返回键进行监听。这样用户想通过返回键退出viewer的时候没有反应。我们就只能自己写关于返回按键的监听了。有点不方便。希望作者能添加针对andoird返回键的监听回调

**Comment by giantss** [comment]
@uuau99999 你点返回键是要关闭当前的Model，还是需要返回到上一张浏览的图片

**Comment by uuau99999** [comment]
关闭当前model。我已经通过在model上加返回键监听实现这个功能了。

**Comment by giantss** [comment]
本来就是监听Model的事件来实现的
