### ISSUE TITLE
好像阻止了android 的back键盘监听~

### ISSUE THREAD

**Issue by yuanji123** [ascoders/react-native-image-viewer#12]
BackAndroid.addEventListener('hardwareBackPress', this.back);  浏览大图的时候监听不了这个

**Comment by ascoders** [comment]
这个插件不会干扰监听物理键的，它只会截断作用范围内UI的手势

**Comment by yuanji123** [comment]
是我的问题

**Comment by lixj0126** [comment]
是什么问题呢？我也遇到了

**Comment by aijason** [comment]
什么原因？

**Comment by aijason** [comment]
我的安卓点击虚拟返回键没有效果

**Comment by aijason** [comment]
@yuanji123 你是怎么解决的？

**Comment by tosslee** [comment]
如果是跟例子一样用Modal包着ImageView，给onRequestClose传一个函数控制visible属性就行了

**Comment by fssantos** [comment]
@tosslee your solution is perfect. I'll just translate it.

> 如果是跟例子一样用Modal包着ImageView，给onRequestClose传一个函数控制visible属性就行了

Translation: If you're using a `<Modal>` just pass it `onRequestClose` props with your control state boolean toggle function.

Example:

```
//render 
       <Modal visible={this.state.isFullscreen} transparent={true}
          onRequestClose={() => { this.toggleFullscreen(false) }}>{...}</Modal>

  toggleFullscreen = (val) => {
    this.setState((prevState) => ({
      isFullscreen: val
    }))
  }

```
