### ISSUE TITLE
iOS 加载本地图片报错

### ISSUE THREAD

**Issue by fenglu09** [ascoders/react-native-image-viewer#124]
RT，加载网络图片没有问题，但是加载本地图片（从相册选择的图片）时，
就报如下错误：
![image](https://user-images.githubusercontent.com/12250129/34658515-a41039e2-f46a-11e7-9ed8-e249a6734be8.png)

版本： 2.0.14
RN: 0.48.2

update: 更新版本到 2.0.18也不行

**Comment by fenglu09** [comment]
问题解决了，是数据的问题

**Comment by fantasyStyle** [comment]
@fenglu09 你好 能说下加载本地相册中的图片你的数据格式吗，我这边显示不出来

**Comment by fenglu09** [comment]
@fantasyStyle  时间有点久了，现在我们也没有用着插件了。当时好像是传入数据的格式问题。
