### ISSUE TITLE
changing imageurl produce error

### ISSUE THREAD

**Issue by koswarabilly** [ascoders/react-native-image-viewer#128]
the problem is , i load my picture uri then set it to the local storage then paste it to a state that the imageviewer get the data from, and if the state changed (especially add new data) it error out while deleting data works fine, i have found my own solution by setting the state to null back before passing data again. but i think this is a warning that will want to be considered. 

but if you think this will not be an issue in the future you may close this issue immediately.

i feel the need of sharing my experience.

**Comment by ParthNandaniya** [comment]
same problem !!
only somwtimes error occure, error said "can't read property 'url' of undefined" but it's actually pass an array of all urls which comes from redux store.
is their any solution for this ??
![err github](https://user-images.githubusercontent.com/30195101/41865052-97d1af7e-78c9-11e8-8a41-b3aea5599d83.PNG)

**Comment by ascoders** [comment]
Can you give a minimum demo code? So i can debug it.

**Comment by ParthNandaniya** [comment]
sry it's my mistake, i couldn't pass index key properly in array which i pass in imageUrls.
so sry about that.

**Comment by ascoders** [comment]
@ParthNandaniya all right, so this issue seemed can be closed.
