### ISSUE TITLE
安卓ios真机上滑动的时候很卡，这个怎么解决

### ISSUE THREAD

**Issue by guoguoss** [ascoders/react-native-image-viewer#129]

**Comment by ascoders** [comment]
You can use debug mode following the readme, and catch the problem.

**Comment by tianweicc** [comment]
@ascoders 遇到一样的问题 真机上很卡顿。。

**Comment by ascoders** [comment]
非常抱歉，是重渲染导致的，已经发布了新版解决此问题：2.0.19
