### ISSUE TITLE
滑动时闪烁

### ISSUE THREAD

**Issue by luojf945** [ascoders/react-native-image-viewer#133]
测试环境：IOS9.3模拟器
左滑或右滑到下一张图片，发现会出现闪烁现象
录制屏幕截取帧发现，中间有一帧黑屏
![1517310476023](https://user-images.githubusercontent.com/1042134/35563219-00d2a826-05f1-11e8-90bf-205bb0750639.jpg)
![1517310487063](https://user-images.githubusercontent.com/1042134/35563229-06550afa-05f1-11e8-93c0-3450dad05a53.jpg)
![1517310493246](https://user-images.githubusercontent.com/1042134/35563233-09cc11ba-05f1-11e8-9153-ac6918bc75cf.jpg)

**Comment by ascoders** [comment]
非常抱歉，是重渲染导致的，已经发布了新版解决此问题：2.0.19

**Comment by luojf945** [comment]
效率太高了，棒棒棒！我试着解决了下，水平不够。只能提bug哈
