### ISSUE TITLE
How to loading render center

### ISSUE THREAD

**Issue by herarya** [ascoders/react-native-image-viewer#135]
hi @ascoders how to set loadingRender to center position,

**Comment by yazhengwang** [comment]
@herarya I fixed like this 
![image](https://user-images.githubusercontent.com/14901532/35719896-60f7821c-0826-11e8-8bd1-f97f91f96c86.png)

**Comment by herarya** [comment]
@yazhengwang thanks, i follow you code, loader indicator still on top position / header bar

**Comment by prospegto** [comment]
@herarya within a <View> with justifyContent: 'center' and alignItems: 'center'

**Comment by jiyeon-dino** [comment]
@herarya how to solved it?

**Comment by mynamespace** [comment]
This works for me:

```javascript
loadingRender={() => (
    <ActivityIndicator
      color={colors.defaultPrimaryColor}
      size="large"
      style={{
        height: Dimensions.get('window').height,
        alignItems: 'center',
        justifyContent: 'center',
      }}
    />
)}
```

**Comment by ascoders** [comment]
It looks like the problem has been solved.
