### ISSUE TITLE
Cannot read property 'startswith' of undefined

### ISSUE THREAD

**Issue by shekharskamble** [ascoders/react-native-image-viewer#138]
![screenshot_20180205-205248](https://user-images.githubusercontent.com/8002785/35805500-17d2db8e-0ab7-11e8-8f23-0324b0b297ad.png)

Hi, I am trying to show images in the image viewer using 'react-native-image-zoom-viewer' library do we have to supply images array like given in the example (url: ...)?

When I user images array looks like below I get this error. 

![image](https://user-images.githubusercontent.com/8002785/35805615-840cbdb0-0ab7-11e8-8bc1-3a663c20b96c.png)

Please help!!

**Comment by TDLehman** [comment]
ImageViewer is actually expecting an array of objects, not strings. Your array should be:
[{ url:"https://firebase...}, {url:"https://secondUrl"}]. 

you can use the map function to fix your array.
images.map( (imageUrl) => { return { url: imageUrl } })

**Comment by shekharskamble** [comment]
So Sorry for late reply I got it working thank you...
