### ISSUE TITLE
可以给示例代码那样结构再自定义加标签吗？

### ISSUE THREAD

**Issue by Tennesseesunshine** [ascoders/react-native-image-viewer#139]
现在想给加一个TouchableHighlight标签，控制点击图片以外区域关闭图片预览。但是一直报错。
<Modal animationType={'fade'} transparent={true}>
    <TouchableHighlight underlayColor='transparent' onPress={this._hideImage} >
        <ImageViewer imageUrls={[{url:realImagePath}]}/>
    </TouchableHighlight> 
</Modal>
只能是modal套ImageViewer吗？

**Comment by ascoders** [comment]
不是，可以任何元素包裹的，最外层只是个 `View`: https://github.com/ascoders/react-native-image-viewer/blob/master/src/image-viewer.component.tsx#L694
