### ISSUE TITLE
安卓上本地图片无法显示

### ISSUE THREAD

**Issue by pywfun** [ascoders/react-native-image-viewer#14]
调试看是在prefetch的时候，一直进的是
function () {
                        imageStatus.status = 'fail';
                       saveImageSize();
                    }

**Comment by ascoders** [comment]
可能在安卓上本地图片不支持 preFetch

**Comment by sunyingming** [comment]
问题解决了吗？

**Comment by ascoders** [comment]
最近略忙，解决速度会比较慢，麻烦各位同学也帮忙调研一下，preFetch是为了获取图片是否在加载中的状态，或者是判断本地图片压根就略过这一步会比较好？
还有本地图片是啥格式的，我可以做个规则，直接把本地图片设置为加载完毕状态就可以了。

**Comment by sunyingming** [comment]
你好，我在使用的时候发现加载图片的时候会有些慢。看了一下源码。发现使用了这两个函数。
preFetch是为了获取图片是否在加载中的状态，getSize获得图片的大小。
preFetch和getSize调用的时候分别去请求了，而且preFetch会cache到disk中，个人认为这样导致了加载慢。
1.显示图片的大小可以以props方式让用户自己设置。
2.图片的加载状态可以使用image本身的几个函数（onLoad ，onLoadEnd ，onLoadStart 。。）。
这样会不会好一些呢？也可以解决android prefetch 的问题。

**Comment by ascoders** [comment]
图片显示大小在看大图会有缩放规则：
1. 小于操作区域不缩放
2. 大于操作区域整体缩放至宽或高铺平操作区域

所以我认为图片尺寸用户可以不关注。@sunyingming 提到的 image 自身生命周期建议非常好，我看看能不能在 onLoad 的时候拿到图片尺寸。

**Comment by ascoders** [comment]
@sunyingming `onLoad` 似乎拿不到图片的尺寸

**Comment by sunyingming** [comment]
你好，android本地拿到的图片地址是files://开头的（有特征）；是否可以这样过滤一下？
您这库怎么自己编译呢？谢谢

**Comment by simman** [comment]
可以在外面判断是否为本地图片, 如果是先使用 getSize 获取宽高, 然后传入到 react-native-image-viewer 里面。

```jsx
// 如果是本地图片
Image.getSize(response.uri, (width, height) => {
  this.setState({
    images: [{url: response.uri, width, height}]
  });
}, (error) => {
    
})
```

**Comment by ascoders** [comment]
@sunyingming 运行步骤：

1. 安装这三个依赖 https://github.com/ascoders/react-native-image-viewer/blob/master/package.json#L16
2. 把 image-viewer 文件夹拷贝到项目中（如果没有用ts，先 npm i typescript -g，再执行 tsc 得到产出拷贝进去）
3. 引用路径修改为 image-viewer/image-viewer.component 即可

**Comment by ascoders** [comment]
@simman 这个问题前几天和另一位同学调过了，如果传入 url 同时，还传入了 `width` `height`，那么就直接跳过步骤直接显示，但这样要求预先在外面获取宽高。源码：https://github.com/ascoders/react-native-image-viewer/blob/master/image-viewer/image-viewer.component.tsx#L137

我看了你了pr，如果是本地图片，并没有获取宽高呢，这样还是要从外部传入宽高，那不改也依然满足这个效果。

**Comment by simman** [comment]
@ascoders , pr 与 在外面获取宽高是二取一，都可以实现。
