### ISSUE TITLE
How to open local image?

### ISSUE THREAD

**Issue by nicholaslie90** [ascoders/react-native-image-viewer#145]
I want to open local image similar to the following:

`let images = [{
			url: require('./../assets/images/myimage.jpg'),
		}];`

This produced the following

![](http://i.imgur.com/aG8co29.png)

also tried

`let images = [{
			url:' ./../assets/images/myimage.jpg',
		}];`

This produced the following

![](https://i.imgur.com/5RnC9X6.png)

Nothing's working though. Can anybody help? Thanks.

**Comment by ascoders** [comment]
See #27
