### ISSUE TITLE
怎么现在这么卡，图片都不能放大

### ISSUE THREAD

**Issue by yt7649757** [ascoders/react-native-image-viewer#146]
去年用你这个库，还挺好的，怎么今年用这么卡，图片放大特别卡，而且无效，你是改了什么吗？

**Comment by ascoders** [comment]
版本号是多少？

**Comment by yt7649757** [comment]
我的react-native版本号是0.45.1，，和这个没关系，我发现在那些低版本的安卓机4.x 或5.x那些性能不好的手机上都很卡，在模拟器上还好一点点，，用我自己的手机安卓7.0的感觉要流畅，在一些图文列表的页面中（图片多，列表长）点击小图放大图片那些性能不好的手机会特别卡，而且程序的内存占用特别高

**Comment by ascoders** [comment]
或许可以考虑不使用 Modal 包裹，这个组件可以运行在任何容器下。

另外如果是版本问题，可以指出去年是哪个版本不卡，今年用了哪个版本的 react-native-image-viewer 导致比去年卡？我好对比代码。

**Comment by yt7649757** [comment]
"react-native-image-zoom-viewer": "2.0.10", 

这个是以前我用的版本，，但是图片放大之后移动图片特别的卡，，无论哪个手机无论哪个版本都是这样，你看下能不能优化

**Comment by yt7649757** [comment]
不好意思，这个问题可以close了，之前我的代码写的有问题，导致很卡，，和你的库没关系，现在我弄好了，不卡了，图片放大移动也是比较流畅的

**Comment by ascoders** [comment]
好的。
