### ISSUE TITLE
Iphone X Support

### ISSUE THREAD

**Issue by ejkkan** [ascoders/react-native-image-viewer#148]
Closing X button will be covered by iphone x header

**Comment by ascoders** [comment]
Can you give a snapshot here?

**Comment by ejkkan** [comment]
![iphonex](https://user-images.githubusercontent.com/32518962/37085696-fde199b2-21f5-11e8-9940-57c8d0e15f5f.png)

**Comment by ascoders** [comment]
Can you pick some code? `react-native-image-viewer` does not contain the X button UI, it's confusing  to see it.

**Comment by ejkkan** [comment]
Totally my bad, it was our own implementation on the close button. Sorry.
