### ISSUE TITLE
请问如何自己编译这个工程

### ISSUE THREAD

**Issue by simman** [ascoders/react-native-image-viewer#15]
有几个功能想要添加：
1、双击放大、还原
2、图片滚动后，上一张恢复正常大小。

**Comment by ascoders** [comment]
这个主要是模仿微信做的，微信第二点是不恢复正常大小的，不过要做的话可以加个可选参数。
这个工程依赖其它自己组件库，自己编译的话，把 `https://github.com/ascoders/react-native-image-viewer/blob/master/image-viewer/image-viewer.component.tsx` 做如下替换：

```typescript
import {autoBindClass} from '../../auto-bind/index'
import {TransmitTransparently} from '../../transmit-transparently/index'
import ImageZoom from '../../image-zoom/index'
```

```typescript
import {autoBindClass} from 'nt-auto-bind'
import {TransmitTransparently} from 'nt-transmit-transparently'
import ImageZoom from 'react-native-image-pan-zoom'
```

这三个库单独npm装下即可，`tsconfig` 参考这个 https://github.com/nt-team/design/blob/master/tsconfig.json

**Comment by ascoders** [comment]
另外，双击放大我也想加，最近加班一直没来及，如果你加上了，非常欢迎给我提pr

**Comment by ascoders** [comment]
已修复源码的引用路径，将整个源代码拷贝到工程，安装上package.json里的依赖就可以跑起来。

**Comment by Thyiad** [comment]
对呀，是typescript的，都不知道怎么编译。。

**Comment by ascoders** [comment]
支持一键编译了，npm run tsc 即可。
