### ISSUE TITLE
Hard coded source prop of <Image>

### ISSUE THREAD

**Issue by xyzzyxyzzy0077** [ascoders/react-native-image-viewer#159]
Hi, just failed to use a local image and dug a little into the implementation of source prop:

`<Image
                style={{ ...this.styles.imageStyle, width, height }}
                source={{ uri: image.url }}
              />`

Where the source is hard coded and anything like `source={require('../...')}` to load local image is impossible.

Will create a PR for this

**Comment by ascoders** [comment]
Great idea!

**Comment by ascoders** [comment]
@zamponotiropita 

Try this:

```typescript
<ImageViewer imageUrls={[{
    props: {
        source: require('../background.png')
    }
}]}/>
```

**Comment by zamponotiropita** [comment]
No, I get the issue described in this issue: TypeError when a local file is set #179 
Please re-open.
