### ISSUE TITLE
图片加载失败,导致无法继续

### ISSUE THREAD

**Issue by astulip** [ascoders/react-native-image-viewer#16]
如果中间有一张图片加载失败后. 会去加载默认图片.这个时候.无法继续查看下一张图片.上一张图片也无法查看.导致界面卡死.

**Comment by ascoders** [comment]
已发布最新版修复了这个问题：1.2.27

**Comment by astulip** [comment]
感谢, 如果没有回应呢.我就打算重新你的代码了. 后面的如果遇到了.问题也还有请教呢
楼主是否能加下QQ:２７７２１５２３７
