### ISSUE TITLE
Can I pass headers parameters to image source?

### ISSUE THREAD

**Issue by championboylay** [ascoders/react-native-image-viewer#161]
We do need to pass http headers for retrieving images. 

>  <Image source={{
>       uri: 'https://facebook.github.io/react/img/logo_og.png',
>       method: 'POST',
>       headers: {
>         Pragma: 'no-cache'
>       },
>       body: 'Your Body goes here'
>     }}
>     style={{width: 400, height: 400}} />

Can I add implement like this?
```
import { Modal } from 'react-native';
import ImageViewer from 'react-native-image-zoom-viewer';

const images = [{
    url: 'https://avatars2.githubusercontent.com/u/7970947?v=3&s=460',
   headers: {
        Pragma: 'no-cache'
      }
}, {
    url: 'https://avatars2.githubusercontent.com/u/7970947?v=3&s=460',
   headers: {
        Pragma: 'no-cache'
      }
}, {
    url: 'https://avatars2.githubusercontent.com/u/7970947?v=3&s=460',
   headers: {
        Pragma: 'no-cache'
      }
}]

export default class App extends React.Component {
    render: function() {
        return (
            <Modal visible={true} transparent={true}>
                <ImageViewer imageUrls={images}/>
            </Modal>
        )
    }
}
```

**Comment by ascoders** [comment]
@championboylay  Thanks for your advice! In `2.1.2` we can pass `headers` to image throw `props`:

```typescript
const images = [{
    url: 'https://avatars2.githubusercontent.com/u/7970947?v=3&s=460',
    props: {
        headers: {
            Pragma: 'no-cache'
        }
    }
}
```

**Comment by mohitaddval** [comment]
Hi, I am trying to use headers with the below code but it is not working for me, Can anybody help here:

[{
          url: document.urls.original,
          props: {
            headers: {
              Authorization: `Bearer ${userInfo.auth_token}`
            }
          }
 }]

**Comment by divisble** [comment]
> Hi @ascoders , I am trying to use headers with the below code but it is not working for me, Can anybody help here:
> 
> [{
> url: document.urls.original,
> props: {
> headers: {
> Authorization: `Bearer ${userInfo.auth_token}`
> }
> }
> }]

@mohitaddval 
For me working something like that:
```

//Get width/height:
import {Dimensions} from "react-native";
const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;

//Array with images:
{
    url: x.payload.image.thumb_urls.md,
    width: windowWidth,
    height: windowHeight,    
    props: {
        source: {
            headers: {
                'x-authorization': 'Token ' + this.props.token,
            }
        },
    }
}
```

It's working like a charm without problems!
Note:
When I didn't set width/height propert then I got black screen for every image except the first one. This is a workaround for that problem (mentioned in this thread and anothers in this repo)
