### ISSUE TITLE
当图片数量过多时,滑动特别卡顿,怎么解?

### ISSUE THREAD

**Issue by CJELLYS** [ascoders/react-native-image-viewer#163]

**Comment by qq326646683** [comment]
+1

**Comment by CoderSwitch** [comment]
+1

**Comment by ascoders** [comment]
It might be a good way to destroy the non current image DOM? Any one want to make a pr?

**Comment by qq326646683** [comment]
“destroy the non current image DOM”
hi, ascoders,what's this mean? Can you elaborate?

**Comment by ascoders** [comment]
@qq326646683 Just do as [react-infinite](https://github.com/seatgeek/react-infinite) do.

**Comment by qq326646683** [comment]
hi,ascoders,I use Paging to deal with this question, but when I page+1 ,it will show last page image firstly. How can I fix it @ascoders

**Comment by qq326646683** [comment]
like this:http://7xt3sl.com2.z0.glb.qiniucdn.com/test.mp4

**Comment by qq326646683** [comment]
hi,ascoders,can you make it by flatList?

**Comment by ascoders** [comment]
Hi @qq326646683 , 2.2.0 optimizes the performance of showing picture, display only the picture of the current window and another two pictures before and after.

**Comment by qq326646683** [comment]
多谢
