### ISSUE TITLE
安卓显示无法显示本地相册路径图片

### ISSUE THREAD

**Issue by CJELLYS** [ascoders/react-native-image-viewer#164]

**Comment by CJELLYS** [comment]
安卓从本地相册取出图片,本地路径如 {uri: 'content://media/external/images/media/72684'},组件就无法显示了,普通的<Image> 组件可以显示这个路径

**Comment by ascoders** [comment]
安卓的格式为 `file:///sdcard/xxx.jpg`，见 #36
