### ISSUE TITLE
android does not support <StatusBar/> with translucent 

### ISSUE THREAD

**Issue by uuau99999** [ascoders/react-native-image-viewer#165]
When using StatusBar and setting translucent true in android, the full screen image viewer still keeps the default status bar offset which leave a blank block in height of about 20. However, ios works just fine.

**Comment by KA5558** [comment]
This link can help you.
[(https://github.com/facebook/react-native/issues/7474#issuecomment-288814366)]

**Comment by KA5558** [comment]
This link can help you.
[](https://github.com/facebook/react-native/issues/7474#issuecomment-288814366)

**Comment by KA5558** [comment]
This link can help you.
[](https://github.com/facebook/react-native/issues/7474#issuecomment-288814366)

**Comment by jessietang** [comment]
i met the same question. and i use react-native-modalbox to wrap the ImageViewer component, it has been fixed.

**Comment by Navipro70** [comment]
If somebody face this issue, know, you can use `statusBarTranslucent` for Modal props (default modal from react-native) and it works ok.
