### ISSUE TITLE
Different image sizes problem

### ISSUE THREAD

**Issue by keech** [ascoders/react-native-image-viewer#167]
If I have image1{1242, 828}  and image2{1200, 830}  and move from image1 to image2 and back to image1, image1 would be displayed strangely.

<img width="414" alt="2018-04-18 19 29 57" src="https://user-images.githubusercontent.com/6279099/38926828-ebc01c94-433e-11e8-94d5-cb2f3bda061d.png">
<img width="414" alt="2018-04-18 19 29 59" src="https://user-images.githubusercontent.com/6279099/38926834-eea5b360-433e-11e8-971e-04dcb7fb84ca.png">
<img width="414" alt="2018-04-18 19 30 01" src="https://user-images.githubusercontent.com/6279099/38926837-f160542a-433e-11e8-8f62-5b1c7144b233.png">

**Comment by keech** [comment]
@ascoders Could you tell me how to fix this probelm??

**Comment by keech** [comment]
@ascoders Any suggetions??

**Comment by ascoders** [comment]
![66666](https://user-images.githubusercontent.com/7970947/39343100-b999b1fa-4a0d-11e8-9b37-eda609945ecc.gif)

Hi @keech, i can't reproduce this bug.

**Comment by keech** [comment]
@ascoders Oh, sorry... The latest version has solved this issue.
Thank you for your comfirmation +1
