### ISSUE TITLE
TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by d41z** [ascoders/react-native-image-viewer#176]
Hi, I am trying to show images in the image viewer using 'react-native-image-zoom-viewer', using the basic usage of example.
but i understand the error.
I'd appreciate your help.
[](url)

![github1](https://user-images.githubusercontent.com/16368170/39447714-0f417d9e-4c99-11e8-9f76-0b74d702ccb4.png)
![github2](https://user-images.githubusercontent.com/16368170/39447719-15bfa010-4c99-11e8-85ce-12765701fa0e.png)

`  class ImageGallery extends Component{

      constructor(props){
      super(props)
      this.state = {
        dataImage: [],
        allimages: [],

      }
    }

    componentDidMount(){

      const { params } = this.props.navigation.state;
      console.log("PARAMS DE GALERIA : ", params)
      var url = 'http://******************/media?parent=' + params.id.toString()

      return fetch(url)
      .then((response) => response.json())
      .then((responseJson) => {
      

        this.setState({
          dataImage: responseJson,
          isLoading: false,

        }, function(){
          this.obtenerImage()

        });

      }).catch((error) =>{
         alert(error, 'No tienes conexion a internet')
      });

      
    }

    obtenerImage(){
      var imagenes = [];
        for (var i = 0; i < this.state.dataImage.length; i++) {
              imagenes[i] = {url: this.state.dataImage[i].source_url}
            }    
      
      

      this.setState({allimages: imagenes})

    }

    render(){
      console.log("???????: ",this.state.allimages)
    

      return (

            <Modal onRequestClose={() => null} visible={true} transparent={true}>
                <ImageViewer imageUrls={this.state.allimages}/>
            </Modal>

       
        );
    }
  }`

**Comment by ascoders** [comment]
Please try `2.2.1`?

**Comment by d41z** [comment]
It's work!
