### ISSUE TITLE
Remove 1/1 from header when number of pictures is 1

### ISSUE THREAD

**Issue by vetrslav** [ascoders/react-native-image-viewer#181]
![image](https://user-images.githubusercontent.com/20933356/39675155-c66dde98-515f-11e8-9802-2ae39842907b.png)
Hi is it possible to remove 1/1 from header?
It's ok when we have more then 1 picture, but in case of 1 i need to remove 1/1.

**Comment by ascoders** [comment]
You can rewrite `renderIndicator`: https://github.com/ascoders/react-native-image-viewer#props

**Comment by vetrslav** [comment]
![image](https://user-images.githubusercontent.com/20933356/39687467-35684da2-51d7-11e8-90dd-f69b357c31af.png)

**Comment by vetrslav** [comment]
My fail, all works fine, thanks
