### ISSUE TITLE
saveToLocalByLongPress无效

### ISSUE THREAD

**Issue by cleverMod** [ascoders/react-native-image-viewer#182]
saveToLocalByLongPress={true} 但是长按无反应

**Comment by tong233** [comment]
the same, version 2.2.3

**Comment by hds220** [comment]
the same 2.2.5

**Comment by tonlen** [comment]
Same issues

**Comment by ascoders** [comment]
Sorry, i have fixed it too later.

**Comment by tonlen** [comment]
Excellent work, thank you! 👍🏻

**Comment by IrinaOvdii** [comment]
I use 2.2.13 but it does not work
