### ISSUE TITLE
No suitable image URL loader found for (null) on iOS

### ISSUE THREAD

**Issue by janlonden** [ascoders/react-native-image-viewer#186]
I get this error message on iOS:

```
No suitable image URL loader found for (null)

-[RCTImageLoader _loadURLRequest:progressBlock:completionBlock:]
RCTImageLoader.m:439

__118-[RCTImageLoader _loadImageOrDataWithURLRequest:size:scale:resizeMode:progr...
```
My code looks like this:

```
<ImageViewer
  imageUrls={[
    {
      props: {
        source: require('src/assets/images/map.png')
      }
    }
  ]}
  renderIndicator={() => null}
/>
```

**Comment by ascoders** [comment]
Hi @jakewtaylor ,thanks for report this bug, can you upload the `src/assets/images/map.png`? i'll try to reproduce this issue.

**Comment by janlonden** [comment]
Here you go:

![map](https://user-images.githubusercontent.com/12981082/40348661-97cce2ea-5da4-11e8-9560-b216b6cef447.png)

**Comment by ascoders** [comment]
![image](https://user-images.githubusercontent.com/7970947/40349267-af26dc64-5dd8-11e8-87c1-e9475d017db8.png)

@janlonden It work fine until i renamed it in whole english words. Here is my config:

```json
{
  props: {
    source: require("./img_other.png")
  }
}
```

I guess this problem not caused by this library? Try to rename it, or use relative path.

**Comment by pw1992519** [comment]
你好我也出现了这种情况，配置什么都是照着复制粘贴的，也是在ios上在使用source属性的时候报这个错，有什么解决方法吗？

**Comment by janlonden** [comment]
@ascoders I've tried using a relative path, other file formats and file names, but nothing helps.

Thank you for your time.

**Comment by ascoders** [comment]
You can clone this project, and run in expo, the doc [is here](https://github.com/ascoders/react-native-image-viewer#development-pattern). The demo entry is `demo/App.js`.

I'm sorry, because I can't resume it now, i haven't got a clue yet.

**Comment by yasinugrl** [comment]
+1 I get this issue

**Comment by airingursb** [comment]
+1 I get this issue

**Comment by ascoders** [comment]
@airingursb @yasinugrl Sorry i can't reproduce this issue, you can fork this repo, and reproduce this bug by changing [demo source code](https://github.com/ascoders/react-native-image-viewer/blob/master/demo/App.js#L12).

[Develop docs](https://github.com/ascoders/react-native-image-viewer/blob/master/readme.md#development-pattern).

**Comment by xianglinhe** [comment]
By adding an empty url solved my problem.
```
{
        url: '',
        props: {
            source: require("./img_other.png")
        }
},
```

**Comment by CarisL** [comment]
maybe should update readme hhh～

**Comment by dan-arkhipov** [comment]
This readme is a JOKE, could you please add all information about object properties needed for this:                 <ImageViewer imageUrls={images}/>

**Comment by ascoders** [comment]
![image](https://user-images.githubusercontent.com/7970947/56101920-3ce7d600-5f5b-11e9-9192-320c1111cabf.png)

I'm already added this, if there is something else, it's awesome to send a PR 💗。
