### ISSUE TITLE
warning key?

### ISSUE THREAD

**Issue by d41z** [ascoders/react-native-image-viewer#189]
![githubhelp](https://user-images.githubusercontent.com/16368170/40551370-add519dc-600a-11e8-8b53-893314857cc9.png)

First of all, this is beautiful and thanks for sharing.
I have tried to resolve the issue of the key and can not find where I can enter, maybe this is not your problem but I would appreciate if you could help me.

the images are shown perfectly, only that I can not fix this warning

**Comment by viko42** [comment]
If you are using .map function, you should use this:  Array.map((value, key) => {
<Component key={key}>
</Component>
})

**Comment by ascoders** [comment]
Yes, as @viko42 said.
