### ISSUE TITLE
Remove caption

### ISSUE THREAD

**Issue by ganeshhfs** [ascoders/react-native-image-viewer#191]
Hi,

I am using  react-native-image-viewer in my one of sample project.I don't to want show white caption as (1/10) at top of screen of image so how can i remove that caption or may it possible to hide from image zoom screen?.

Thanks and regards,
Ganesh Madane

**Comment by nbastoWM** [comment]
Just add the props:
```renderIndicator={() => {}}```

**Comment by ascoders** [comment]
Right, thanks @nbastoWM !

**Comment by ganeshhfs** [comment]
Thanks very much nbastoWM. I will try this solution.
