### ISSUE TITLE
index is not working 

### ISSUE THREAD

**Issue by abdurrahmankhamis** [ascoders/react-native-image-viewer#194]
Hi ,

I have used the  a code for the gallery like this 
`import ImageViewer from 'react-native-image-zoom-viewer';`

`<ImageViewer  imageUrls={imagesUrls} index="5" />`

The initial index coming as "51"  instead of expected index 5

Regards,
Abdo

**Comment by nicomontanari98** [comment]
@abdurrahmankhamis index prop is of type number not string!
Try it:
`<ImageViewer imageUrls={imagesUrls} index={5} />`

**Comment by ascoders** [comment]
Thanks @nicomontanari98, that's right.
