### ISSUE TITLE
for ios only???

### ISSUE THREAD

**Issue by xiaozhicheng** [ascoders/react-native-image-viewer#2]
This error is caused by a @providesModule declaration with the same name across two different files.

**Comment by ascoders** [comment]
Hi, Both Android and IOS are compatible. But Android has not yet been tested.

**Comment by xiaozhicheng** [comment]
why all files'type is .ts

**Comment by ascoders** [comment]
After npm install, the package will use lib/index.js, these files use js suffix, the entrance in the package.json: https://github.com/ascoders/react-native-image-viewer/blob/master/package.json#L5
