### ISSUE TITLE
IOS放大图片,用力滑动到下一页有BUG。

### ISSUE THREAD

**Issue by suinia** [ascoders/react-native-image-viewer#20]
安卓没有弹性滚动，IOS有就会出现这个BUG。把图片放大。用力滑动，一直显示loading加载

调试发现image-pan-zoom组件里面的horizontalWholeOuterCounter值是0导致不调用handleHorizontalOuterRangeOffset
我现在直接把handleResponderRelease回调里面给 if (vx > 0.7) {if (vx < -0.7) {加上handleHorizontalOuterRangeOffset回调解决

**Comment by ascoders** [comment]
我在加大力度滚动时，调用加载图片方法解决了这个问题，v1.2.39

**Comment by suinia** [comment]
速度很快嘛，哈哈
