### ISSUE TITLE
Flip effect doesn't work anymore with latest version

### ISSUE THREAD

**Issue by paolospag** [ascoders/react-native-image-viewer#200]
Hi,
I just updated the package 'react-native-image-zoom-viewer' to the latest version (2.2.6) and I noticed that flip/swipe effect doesn't work... 
In particular: the images continue to change, but the scrolling effect that shows a little bit of image before and after doesn't work anymore.

I refer to this effect:
https://cloud.githubusercontent.com/assets/7970947/21086300/388dedfc-c056-11e6-955e-0a2a0b541f7f.gif

I'm trying in Android environment, so I don't know if on iOS continues to work.

Any idea?
Thanks

**Comment by ascoders** [comment]
Hi @paolospag ,can you provide a gif or video?

**Comment by paolospag** [comment]
Hi @ascoders ,
if I try to record device screen, the image-changing stops working and I remain stuck to the same image.
I'm unable to reproduce this problem.

How can I do?

**Comment by ascoders** [comment]
Sorry i have no android device, and you can debug source code for this lib follow [this docs](https://github.com/ascoders/react-native-image-viewer#development-pattern), and i can solve this problem if you find some breakthroughs, but now i can't find and point.

**Comment by paolospag** [comment]
Hi @ascoders sorry for my late answer.
I tried too on iOS and I noticed the same bug. Probably the issue is related only to my project, so I hypothesized that it could be caused by an incompatibility with another package.

If you give me an e-mail, I can try to send you a video. 
I could post the list of my package.json dependencies if it can help you.
Are you aware of an incompatibility with **react-native-splash-screen**? The problem arose after I installed this.

Thanks

**Comment by ascoders** [comment]
@paolospag you can send video to www.ziyihuang@gmail.com, and it's better to addon your whole code and packages. Thanks!

**Comment by fallenner** [comment]
the issue still exits in latest version(2.2.12)(android).  however, 2.2.5  work as expected.

**Comment by fallenner** [comment]
@ascoders @paolospag   I found it's  caused by  react-native-image-pan-zoom. react-native-image-pan-zoom(2.1.3) work as expected.  Flip effect doesn't work anymore in the latest version (2.1.6)

**Comment by vvavepacket** [comment]
@ascoders 

See video

https://www.youtube.com/watch?v=FhLoqXuSo2I&index=1&list=UUa1i9DObV-7znyhpfeQ_Thw

Same issue using the latest version

**Comment by vvavepacket** [comment]
i can confirm @fallenner  solution, reverting to 2.1.3 work as expected. why is that

**Comment by ascoders** [comment]
It's a bug from this pr [horizontal bounceback](https://github.com/ascoders/react-native-image-zoom/pull/55), now `react-native-image-zoom-viewer` has fixed it in new version `2.2.13`.

**Comment by paolospag** [comment]
@ascoders ok, after upgrading to 2.2.13 my gallery works as I expect, but now I'm unable to swipe down (both Android and iOS) and consequently to dismiss gallery (just iOS).

Can you solve this too?
