### ISSUE TITLE
【建议】图片放大时翻页和移动动作容易混乱

### ISSUE THREAD

**Issue by ekoooo** [ascoders/react-native-image-viewer#208]
描述：当放大图片时，移动图片容易出现翻页。

建议：当图片放大时，如果图片位置没有到达边缘位置，则进行移动动作，否则进行翻页动作。

版本：`v2.2.8`

**Comment by ascoders** [comment]
That's the current behavior. And if you sliding in a high speed, it will also jump to next image even if current scale is greater than 1. 

So you can slide slowly to avoid jumping.
