### ISSUE TITLE
Configurable UI

### ISSUE THREAD

**Issue by mschipperheyn** [ascoders/react-native-image-viewer#21]
Hi,

it would be nice if the UI could be configurable. Is would suggest allowing for a few additional render methods to the component:

* renderHeader
* renderFooter
* renderIndicator: (currentIndex) => {...} renders the element that is now 1/3 but allows rendering customized versions, e.g. the common method of using little round icons. Commonly, I would expect this below the swipeable view. 
* renderArrowLeft: I would expect to be able to supply components that when clicked animates to the next photo
* renderArrowRight

Given all these elements that people may want to customize, I would suggest almost to leave the whole modal part out of it and just supply the swipeable zoom view.

**Comment by ascoders** [comment]
What you said is very reasonable, I have already finished, the only problem is the arrow cannot respond to the click event, because gestures intercepted, I now have no time to deal with this problem, if the demand is very strong, I will take the time to solve.
