### ISSUE TITLE
When the modal is opened, the image is not displayed, the screen is shown in black

### ISSUE THREAD

**Issue by NdozHH** [ascoders/react-native-image-viewer#211]
I have a swiper with images with an onPress event, when I click on it, the modal opens but the image is not seen, only the black screen and the header 1/3, 2/3, etc. is seen.

The array contains the correct URLs and I'm testing it on Android
![imagen](https://user-images.githubusercontent.com/25773289/42592884-9295d3ca-8510-11e8-95fc-3c618d9aa846.png)

**Comment by NdozHH** [comment]
Solved

**Comment by MNNetcorp** [comment]
@NdozHH how did you solve this problem? I have the same issue and don't have any idea how to fix it.

**Comment by NdozHH** [comment]
@MNNetcorp The array of images must be built this way, with objects and that each one has the url property
![imagen](https://user-images.githubusercontent.com/25773289/42644236-b3318a9c-85c0-11e8-90c8-1fe813a1f85c.png)

**Comment by MNNetcorp** [comment]
@NdozHH thx!
