### ISSUE TITLE
Lagging when slide image

### ISSUE THREAD

**Issue by sinhpn92** [ascoders/react-native-image-viewer#214]
I have implemented `ImageViewer` in my app but when slide image is lagging.
`render() {

        const images = [];
        this.props.navigation.state.params.images.map((image, i) => {
            images.push({
                url: image.link,
            })
        })
        const index = this.props.navigation.state.params.position;
        return (
            <View style={{ backgroundColor: 'black', flex: 1, justifyContent: 'center', alignItems: 'center' }}>
                <ImageViewer imageUrls={images}
                             index={index ? index : 0}
                             style={{flex: 1, width: '100%', height: '100%', backgroundColor: 'black'}}
                             loadingRender={() => <ActivityIndicator animating={true} size={'small'} color={COLOR_PRIMARY} style={{marginTop: 150}}/>}
                             renderIndicator={this._renderImageIndicator}/>

                <TouchableOpacity style={styles.closeButton}
                                  onPress={this._dismissSliderScreen}>
                    <Text style={{ color: COLOR_TEXT_INACTIVE_DISABLE, backgroundColor: 'transparent', fontSize: DIMENSION_TEXT_CONTENT }}>
                        Close
                    </Text>
                </TouchableOpacity>

            </View >
        )
    }`

Have any problem with my implementation?

**Comment by ascoders** [comment]
Can you give a gif or video?

**Comment by sinhpn92** [comment]
@ascoders thank for you support.
this is gif that i recorded: 
[https://imgur.com/a/lSic99l](gif)

**Comment by sinhpn92** [comment]
@ascoders oh i see. I tried and it's working
