### ISSUE TITLE
onClick事件没有触发

### ISSUE THREAD

**Issue by syuenkei** [ascoders/react-native-image-viewer#218]
安卓真机上 点击图片区域或者图片外区域（非长按） 自定义的onClick事件没有触发  而是底部调起了一个menu

**Comment by ascoders** [comment]
You can disable save to camera by passing this props: `onSaveToCamera={false}`.

**Comment by mengbimao** [comment]
加了这个onSaveToCamera={false}还是没反应

**Comment by mengbimao** [comment]
我这个也是安卓的,华为p30PRo,真机和模拟器都是一点图片弹出菜单,就没有触发onclick点击事件呢
