### ISSUE TITLE
index 传值进去显示有问题

### ISSUE THREAD

**Issue by yam963** [ascoders/react-native-image-viewer#221]
例如我传下标2，页数显示21，传3页数显示31，图片显示正常，但是翻页后也会出问题。
![default](https://user-images.githubusercontent.com/13232032/44200253-bf27bc80-a178-11e8-94de-986a86f24f08.png)

**Comment by ascoders** [comment]
确定传的下标是数字吗？？

**Comment by yam963** [comment]
@ascoders 我parseInt转化了一下，可以了。谢谢哦
