### ISSUE TITLE
18:9 full screen support

### ISSUE THREAD

**Issue by FaiChou** [ascoders/react-native-image-viewer#228]
On Mi Mix 2s 18:9 full screen device, the image viewer always(not each time) expose the bottom space.

Code:

```javascript
        <Modal visible={show} transparent={true}>
          <ImageViewer
            style={{flex: 1}}
            imageUrls={viewPhotos}
            index={viewPhotoIndex || 0}
            menuContext={{saveToLocal: '保存到本地相册', cancel: '取消'}}
            onClick={this.closeModal}
            onSave={this._saveImg}
            onSwipeDown={this.closeModal}
            loadingRender={() =>
              <View style={styles.indicator}>
                <ActivityIndicator />
              </View>
            }
          />
     </Modal>
```

Pics:

<img src="https://user-images.githubusercontent.com/18500846/45145734-f1ff2680-b1f3-11e8-8d0b-2dd28a468e94.jpg" width="300" />

---

<img src="https://user-images.githubusercontent.com/18500846/45146051-a6994800-b1f4-11e8-9704-c030a28c5718.png" width="300" />

Environment

```
"react-native": "0.55.4",
"react-native-image-zoom-viewer": "^2.2.7",
```

**Comment by pzw224** [comment]
这个是rn的Modal组件的问题，全面屏无法全屏显示

**Comment by thebinarymutant** [comment]
I had the same issue, it was resolved by my colleague by passing `style = {{ flex: 1, height: '100%'}}` prop to the modal component.

**Comment by FaiChou** [comment]
Yes, it's a bug of rn's Modal
