### ISSUE TITLE
renderFooter无效？

### ISSUE THREAD

**Issue by yang24201** [ascoders/react-native-image-viewer#23]
文档说明中的render回调方法都不能使用吗？

**Comment by ascoders** [comment]
应该生效的，检查下 `renderFooter` 是否是一个函数；渲染内容是否是黑色，被背景盖住导致的。

**Comment by yang24201** [comment]
同样的组件放到renderHeader里面可以看到，放到renderFooter里面就看不到

**Comment by ascoders** [comment]
试试 absolute 定位，怀疑是被挤到下面了
