### ISSUE TITLE
Touch event support on header & footer

### ISSUE THREAD

**Issue by rayhk6** [ascoders/react-native-image-viewer#237]
I would like to implement some touch action on footer & header. Do you have idea roadmap or schedule for this function? Thanks

**Comment by ascoders** [comment]
You can rewrite `renderFooter` and `renderHeader`?

**Comment by rayhk6** [comment]
> Can you rewrite `renderFooter` and `renderHeader`?

sorry, I can't :(

**Comment by ascoders** [comment]
@rayhk6 What a pity, could you tell me what business problems you want to solve?

**Comment by rayhk6** [comment]
@ascoders I just want to add a close button on header instead of using onClick function and some actions on footer.

**Comment by ascoders** [comment]
You can add this button by using `renderHeader`, and listening click event on this button.

**Comment by rayhk6** [comment]
> You can add this button by using `renderHeader`, and listening click event on this button.

I tried touchOpacity but not working

**Comment by nbolender** [comment]
The default indicator component style is overlapping the header component, capturing touches. Working on a PR.

**Comment by ascoders** [comment]
@nbolender thanks! `react-native-image-zoom-viewer` `2.2.22` has been deployed.

**Comment by srimuruganZen** [comment]
> > You can add this button by using `renderHeader`, and listening click event on this button.
> 
> I tried TouchableOpacity but not working

Give position:'absolute' and zIndex:999 to the view and then TouchableOpacity will work

**Comment by akhileshsinha** [comment]
Import TouchableOpacity from 'react-native' instead of  'react-native-gesture-handler'.
