### ISSUE TITLE
Reset zoom programmaly

### ISSUE THREAD

**Issue by DragonSpirit** [ascoders/react-native-image-viewer#238]
Hello! How I can reset zoom from code? resetPosition won't work for this case.

**Comment by MrPluto** [comment]
need this feature too

**Comment by ascoders** [comment]
`resetPosition` will only reset position rather than zoom. Welcome pr @DragonSpirit @MrPluto

**Comment by ascoders** [comment]
Deployed `2.2.19`.

**Comment by braianj** [comment]
Is there an example to woth with resetPosition?
