### ISSUE TITLE
当图片能铺满屏幕高度的时候,数量文字显示不出来,在图片下层

### ISSUE THREAD

**Issue by LDty** [ascoders/react-native-image-viewer#251]
![default](https://user-images.githubusercontent.com/30049714/47195598-2affee80-d38f-11e8-87cf-3b4cca23efbe.png)

like this

**Comment by ascoders** [comment]
看上去是 z-index 设置的问题，pr 的好机会 @LDty

**Comment by LDty** [comment]
计时器的zindex现在是-1,我改成和arrowLeftContainer,arrowRightContainer一样的13 ok嘛?

**Comment by ascoders** [comment]
好的，已发布 `2.2.23`
