### ISSUE TITLE
[Feature request] Needs image caching

### ISSUE THREAD

**Issue by ithieund** [ascoders/react-native-image-viewer#26]
@ascoders ,
This plugin was good. I'm using it in my project.
The only thing I want to suggest is the image caching.

For now, it keeps reloading the image every time the modal is open. That caused a long time of black screen waiting for the image to load. It's extremely bad when loading a large image.

Can you please add image caching in the next release?
Thanks.

**Comment by ascoders** [comment]
This most work is done by [react-native-image-zoom](https://github.com/ascoders/react-native-image-zoom), you can use it with [react-native-cacheable-image](https://github.com/jayesbe/react-native-cacheable-image).
