### ISSUE TITLE
长图放大很模糊, 有办法解决吗?

### ISSUE THREAD

**Issue by FaiChou** [ascoders/react-native-image-viewer#260]
### 代码

App.js

```javascript
import React from 'react';
import { Modal } from 'react-native';
import ImageViewer from 'react-native-image-zoom-viewer';

const images = [{
  url: 'http://userapp.bj.bcebos.com/share/20181108/00002008_20181108_163602_084926393_1',
}]

export default class App extends React.Component {
  render() {
    return (
      <Modal visible={true} transparent={true}>
        <ImageViewer imageUrls={images}/>
      </Modal>
    );
  }
}
```

### 样式

![image](https://user-images.githubusercontent.com/18500846/48191654-a3e7da00-e380-11e8-839c-71b86076d528.png)

### 环境

安卓/iOS 模拟器真机都放大变模糊, 但是下载下来图片是完整的.

```
"react": "16.6.0-alpha.8af6728",
"react-native": "0.57.4",
"react-native-image-zoom-viewer": "^2.2.23"
```

**Comment by jamninetyfive** [comment]
请问你解决了么  这个问题

**Comment by FaiChou** [comment]
@jamninetyfive 没有解决

**Comment by jamninetyfive** [comment]
@ascoders

**Comment by tianweicc** [comment]
@FaiChou @jamninetyfive 请问你们解决了这个问题么

**Comment by hu-qi** [comment]
@FaiChou @jamninetyfive  @tianweicc 请问你们解决了这个问题么

**Comment by hu-qi** [comment]
> @FaiChou @jamninetyfive @tianweicc 请问你们解决了这个问题么

已解决  image 加 resizeMethod={'resize'}

**Comment by zhllucky** [comment]
ios呢。  @hu-qi

**Comment by huhu-mvp** [comment]
fastimage 了解一下

**Comment by Thyiad** [comment]
@hu-qi 这个resizeMethod是加在哪的啊？

**Comment by Thyiad** [comment]
呃，知道了，通过props传进去，ios怎么搞得，你解决没。。
@zhllucky

**Comment by huhu-mvp** [comment]
> @hu-qi 这个resizeMethod是加在哪的啊？
不需要设置resizeMethod ，Android 把overwrite 加进去

**Comment by Thyiad** [comment]
@huhu
overwrite是指？ props.renderImage吗？

**Comment by Thyiad** [comment]
好吧，亲测resizeMethod也没用。
最后修改了源码，图片尺寸大于设备尺寸时，不做缩小处理，同时将pan-zoom的enableCenterFocus设置为false，先这样解决了

**Comment by shenyuanqing** [comment]
用FastImage试试：

```
import FastImage from 'react-native-fast-image';

<ImageViewer
    imageUrls={imageList}
    index={this.state.imageArray.length - 1}
    renderImage={(props)=>{
        return(
            <FastImage {...props}/>
             )
        }}
 />
```

**Comment by suwu150** [comment]
这个问题又得到解决吗

**Comment by tsingroo** [comment]
> 好吧，亲测resizeMethod也没用。
> 最后修改了源码，图片尺寸大于设备尺寸时，不做缩小处理，同时将pan-zoom的enableCenterFocus设置为false，先这样解决了

我这样好像还是很模糊

**Comment by suwu150** [comment]
有人解决该问题吗
