### ISSUE TITLE
Threshold option for swipe down to make it more sensitive

### ISSUE THREAD

**Issue by baophamtd** [ascoders/react-native-image-viewer#262]
Hi there. Thank you for a great plugin. I wonder if it's possible for me to adjust the sensitivity of swipeDown action to kick-in. Right now, I'm just enable swipeDown to hide the ImageViewer, but I feel like I have to really swipe it all the way down to make it happen. Normally, I would have 70% chance.

Disclaimer: My hand size is normal.

**Comment by wack17s** [comment]
@baophamtd As i can see in source files, `react-native-image-viewer` uses `react-native-image-pan-zoom` component and it has `swipeDownThreshold` prop. All you need is add this prop to `react-native-image-viewer` and pass to `react-native-image-pan-zoom`. You are welcome to open PR for this :).

**Comment by wack17s** [comment]
#264

**Comment by baophamtd** [comment]
@wack17s seems like you've already done it. Would you mind to ask for a new version so it can be updated?
Thanks a lot!

**Comment by ascoders** [comment]
@baophamtd `2.2.24` deployed.
