### ISSUE TITLE
Can't load local file with prefix file:/// in IOS devices

### ISSUE THREAD

**Issue by jothikannan** [ascoders/react-native-image-viewer#276]
I am not able to see the local images in the zoom viewer, rather it is not showing any errors, getting the blank screen

File path:

<img width="394" alt="screen shot 2018-12-23 at 9 53 05 pm" src="https://user-images.githubusercontent.com/4100047/50385546-6acfb300-06fd-11e9-8f21-8854d2263dc0.png">

OutPut:
<img width="437" alt="screen shot 2018-12-23 at 9 56 59 pm" src="https://user-images.githubusercontent.com/4100047/50385569-c1d58800-06fd-11e9-9f58-1b40ef9faef5.png">

I am using react native fs for storing the captured images in App's document directory and i am trying to get the path and try to use with component,

Please help

**Comment by jothikannan** [comment]
Fixed it myself

No need of 
```
props: {
        source: require('path')
    }
```

url is enough

**Comment by sajadabasi** [comment]
@jothikannan can you explain how did you solved it?

**Comment by Alb93** [comment]
Putting the URI directly on the url prop (same for remote urls)
