### ISSUE TITLE
saveToLocalByLongPress无法保存 2.2.23版本长按弹出英文按钮，并且没有保存到系统相册

### ISSUE THREAD

**Issue by qubangliuhui** [ascoders/react-native-image-viewer#278]
![3edfcda8-2d70-4a0b-8904-56bf07361299](https://user-images.githubusercontent.com/42051386/50679233-a2aff200-103d-11e9-892b-cd2cbcfa4600.png)

**Comment by qubangliuhui** [comment]
IOS的

**Comment by gromy92** [comment]
同问  请问这个问题何时可以修复

**Comment by qubangliuhui** [comment]
这个问题自己解决吧，调用系统方法保存，然后英文字体改源码吧


发自我的 iPhone

**Comment by ascoders** [comment]
安卓环境需要调用系统方法保存到相册。

**Comment by AceChoong123** [comment]
想請問該如何調用系統方法呢？
