### ISSUE TITLE
onClick return info about the picture

### ISSUE THREAD

**Issue by hamedhemmati** [ascoders/react-native-image-viewer#281]
Thank you for the nice plugin. Is there any way to get the info on the picture that was clicked on with the onClick such as the index number?

**Comment by ascoders** [comment]
@hamedhemmati Hello, what would you want to do when click each picture?

**Comment by hamedhemmati** [comment]
I have 2 ImageView components. One is inside a modal for a fullscreen view and the other is outside and always visible on my screen as a quick preview of the images. When tapping on the images I make the modal visible to basically show the same images in fullscreen. What I want to do is to find out which image was tapped on so I can pass it to the ImageView component inside the modal.

**Comment by hamedhemmati** [comment]
I found another way of doing this. I use the onChange to get the current index and use that get the image info from the data array.
