### ISSUE TITLE
IOS - Landscape not working

### ISSUE THREAD

**Issue by xstable** [ascoders/react-native-image-viewer#282]
On Android, Landscape-Mode works like a charm, but on IOs I've found following behavior: 

Mobile-Device is in Landscape-Mode:
- I click on an Image (Touchable-Opacity set the state `modalShow`
- The Landscape-Mode will be switched to Portrait-Mode, after that the Modal appears
- If I close the Modal, the App switch back to Landscape-Mode.

Any Idea, why this only happend on Iphone, but working well on Android?

**Comment by xstable** [comment]
I solved it. You have to add this to your Modal: 

```
supportedOrientations={['portrait', 'portrait-upside-down', 'landscape', 'landscape-left', 'landscape-right']}
```

**Comment by diamont1001** [comment]
Thank you, buddy.

**Comment by srhtylmz19** [comment]
you saved the day @xstable  <3
