### ISSUE TITLE
安卓隐藏虚拟按键后屏幕高度不对以及建议修改的方法

### ISSUE THREAD

**Issue by LDty** [ascoders/react-native-image-viewer#283]
![c67ef4eebe3db1ce572bdaaaac95431](https://user-images.githubusercontent.com/30049714/51421681-bc743c00-1bdc-11e9-9ed1-b905ffca34f7.jpg)
安卓使用全面屏手势后 获取到的高度依旧是不带虚拟按钮部分的高度。（测试机型 小米mix2 小米8 nokia x6）
推荐解决办法：
          <ImageZoom cropWidth={'100%'}
                            cropHeight={'100%'}...
替代
        <ImageZoom
          cropWidth={this.width}
          cropHeight={this.height}...

**Comment by jamninetyfive** [comment]
怎么隐藏虚拟键的？

**Comment by LDty** [comment]
> 怎么隐藏虚拟键的？

安卓，启用全面屏手势

**Comment by jamninetyfive** [comment]
> > 怎么隐藏虚拟键的？
> 
> 安卓，启用全面屏手势

哦  我以为是有api方法可以隐藏～

**Comment by canyara** [comment]
你需要这个

`render = (): React.Node => {
    const deviceWidth = Dimensions.get("window").width;
    const deviceHeight =
      Platform.OS === "ios"
        ? Dimensions.get("window").height
        : require("react-native-extra-dimensions-android").get("REAL_WINDOW_HEIGHT");

    return (
      <Modal animationType="fade" transparent={true} visible={this.props.visible}>
        <View style={{ width: deviceWidth, height: deviceHeight }}>{this.props.children}</View>
      </Modal>
    );
  };`
