### ISSUE TITLE
How to change key URL on URI? 

### ISSUE THREAD

**Issue by VTSingle** [ascoders/react-native-image-viewer#295]
I have an array 
`[{uri: 'http://aboutreact.com/wp-content/uploads/2018/07/sample_img.png'},{uri: 'http://aboutreact.com/wp-content/uploads/2018/07/sample_img.png'}]`
but the module working only with key URL, how I can change it?

**Comment by dayaki** [comment]
Hi @VTSingle am facing same issue, how are you able to solve it?
