### ISSUE TITLE
Does nothing

### ISSUE THREAD

**Issue by kuriel-trivu** [ascoders/react-native-image-viewer#310]
following the basic sample, does nothing. nothing rendered, nothing visible.

**Comment by mj-haghighiGH** [comment]
images = images.map((image) => {
            return {
                url: 'https://avatars2.githubusercontent.com/u/7970947?v=3&s=460',
                width: image.meta.ImageWidth,
                height: image.meta.ImageHeight,
                props: {
                    source: {
                        uri: image.path
                    }
                }
            };
        });
        return (
            <ImageViewer
                imageUrls={images}
                enableSwipeDown
                onSwipeDown={() => {
                    this.props.navigation.pop()
                }}
            />
        );


do not remove url
