### ISSUE TITLE
Page turn/flip no longer working

### ISSUE THREAD

**Issue by junkdeck** [ascoders/react-native-image-viewer#314]
Swiping the image past the threshold no longer causes the image to smoothly transition to the next.
Instead, it gets stuck, then the next image suddenly jerks into place.
Doesn't seem like a performance issue, as the performance monitor doesn't show any dips in FPS beyond the expected from touch overhead. 
Using 2.2.26. It used to work fine, but uncertain what version that was.

**Comment by SuperBigBang** [comment]
Some problem!

**Comment by junkdeck** [comment]
I've replaced the library with this one instead:
https://github.com/antonKalinin/react-native-image-view

Works much better.
