### ISSUE TITLE
How to add image description caption?

### ISSUE THREAD

**Issue by sunviwo** [ascoders/react-native-image-viewer#318]
Hi,
Great package. I'd like to know whether there is a way to display a description text at the bottom of each image.
By the way, planning to add video player by any chance?

**Comment by DISKONEKTeD** [comment]
you can use the renderFooter prop (it receives a react component, so feed it a view comp with a text comp in it perhaps). Just feed it an array of texts you can set in the state perhaps

**Comment by sunviwo** [comment]
Worked. Thank you.
