### ISSUE TITLE
Zoom doesn't work

### ISSUE THREAD

**Issue by nadav2051** [ascoders/react-native-image-viewer#319]
The functionality of zooming doesn't work, I've explicitly set the enableImageZoom to true and neither double tap to zoom, or pinch to zoom is working.

React Native 0.59.8

**Comment by DISKONEKTeD** [comment]
I'm on 0.59.10, using 2.2.26 and it working fine

**Comment by nadav2051** [comment]
Yep, it was totally my bad, it seems a flex: 1 style to the ImageViewer component brought the zoom back.

**Comment by shengliZh** [comment]
me too, 0.59.8 zoom doesn't work
