### ISSUE TITLE
Android index有问题

### ISSUE THREAD

**Issue by arthasAndDk** [ascoders/react-native-image-viewer#33]
￼
![screenshot_20170316-181957](https://cloud.githubusercontent.com/assets/9312526/23991802/8da3d31a-0a75-11e7-8dbc-e13d28e2b4f7.png)
![screenshot_20170316-181944](https://cloud.githubusercontent.com/assets/9312526/23991846/b6a25c64-0a75-11e7-8fe9-26e685a05c53.png)
如图，一共三幅图，点击第三个，第一个加载不出来
但是我点击第一个，1、2、3可以加载出来，4和5加载不出来

补充：貌似图片比较大才会出现这个bug

**Comment by ascoders** [comment]
应该是图片加载失败了，但是没有传 `failImageSource` 参数，导致显示不出错误图片。

**Comment by RPerkins96** [comment]
<ImageViewer index={2} imageUrls={images}>  does not set the image to the third image.   

The first image is always the default regardless of the value put into index={n}.

Is this a bug?

**Comment by arthasAndDk** [comment]
是的，图片太大，你这边直接显示没有压缩，所以报错了

**Comment by ascoders** [comment]
有没有压缩方案

**Comment by arthasAndDk** [comment]
目前是通过七牛来压缩了图片尺寸，可以正常显示，毕竟android限制了bitmap大小

**Comment by ascoders** [comment]
通过 cdn 解决。
