### ISSUE TITLE
Feature Request: Pagination prop

### ISSUE THREAD

**Issue by iamclaytonray** [ascoders/react-native-image-viewer#334]
Currently, there are no options to adjust the pagination style, or even to completely remove it. Thoughts would be including a `renderPagination={(...) => React.ReactElement}`, or at the very least, `pagination={boolean}`? I'll PR this!

**Comment by 18605161612** [comment]
对了 ，能不能加一个隐藏pagination的方法

**Comment by aajahid** [comment]
`renderPagination={(...) => null}` supposed to work.

And as you can see, you can pass the whole react component, so you are in control whatever you want, including styling.
