### ISSUE TITLE
Caching is not supported

### ISSUE THREAD

**Issue by GS-LiuYang** [ascoders/react-native-image-viewer#343]
Every time you open Modal, you need to retrieve the requested image to get the attributes of the image. This is a very foolish way to make the experience of thieves bad. It's good to browse the local image. Oversize of the network image is a kind of torture, hoping to support caching.

**Comment by GS-LiuYang** [comment]
I apologize for my remarks. When I used the real machine, the cache was successful. I think it might be the reason of the simulator. I'm very sorry.

**Comment by ascoders** [comment]
It doesn't matter. Environmental problems are hard to detect.

**Comment by cybercoder** [comment]
It is possible to use ```react-native-image-cache-wrapper```inside and control cache expiration.
