### ISSUE TITLE
invaild prop 'source' supplied to 'Image'

### ISSUE THREAD

**Issue by zuzuviewer** [ascoders/react-native-image-viewer#35]
我传给imageUrls里的url放的是base64的图片数据，然后显示就提示Invaild prop 'source' supplied to 'Image'，并且源码里的imageInfo的status总是fail，不知道在url上是不是有什么限制，还是通过什么方式可以解决

**Comment by ascoders** [comment]
加上 width height 参数，可以跳过状态监测，试试看？

**Comment by zuzuviewer** [comment]
@ascoders ,不好意思，我不确定在哪里添加这两个参数，还烦请告知

**Comment by zuzuviewer** [comment]
@ascoders ，加了这两个参数后走的是`if (imageInfo.status === 'success' && _this6.props.enableImageZoom)`，但是我的modal没有显示图片，我在这个if里面打印了image.url是有图片数据的，并且我的modal是全屏的只用来加载ImageViewer组件，再也没有其它组件

**Comment by ascoders** [comment]
一切都正确应该能显示的呀，都追到这一步了，再加把劲调研一下，看看可否提个pr？
