### ISSUE TITLE
Usage of deprecated react methods

### ISSUE THREAD

**Issue by saurabh1234** [ascoders/react-native-image-viewer#350]
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

**Please update the following components: ImageViewer**

setUpDeveloperTools.js:73 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ImageViewer

When can we expect this to be updated ?

**Comment by janva255** [comment]
+1

**Comment by ascoders** [comment]
PR welcome.

**Comment by ArtemKolichenkov** [comment]
@ascoders I will take a look at it right now, should be straightforward fix.

**Comment by ksetrin** [comment]
@ascoders did you update npm after the merge?
