### ISSUE TITLE
failImageSource 怎么使用本地图片

### ISSUE THREAD

**Issue by a728384698** [ascoders/react-native-image-viewer#354]
![WeChatda4c02f73471a2e750e2eaa9ea8c563b](https://user-images.githubusercontent.com/7380874/67071636-a6b89500-f1b5-11e9-985b-0e4fc7989993.png)

uri:直接是一个网络请求的图片地址可以；像上面这样无效，我怎么样使用本地中的地址

**Comment by diamont1001** [comment]
require().uri

**Comment by staceypyee** [comment]
Is failImageSource part of imageUrls or within <ImageViewer>?

**Comment by diamont1001** [comment]
文档写的是 url，按文档来试下吧：
failImageSource:
```
string, object
 {url: string}
```

或者你提供个最小能复现 demo，贴点代码出来也好啊

**Comment by staceypyee** [comment]
This is working: 
`
 <ImageViewer
          imageUrls={images}
          failImageSource={{
            url: 'https://avatars2.githubusercontent.com/u/7970947?v=3&s=460',
            width: Dimensions.get('window').width,
            height: Dimensions.get('window').width,
          }}
        />
`





This is not working
```
 <ImageViewer
          imageUrls={images}
          failImageSource={{
            url: require("../../xxx.png").uri,
            width: Dimensions.get('window').width,
            height: Dimensions.get('window').width,
          }}
        />
```

**Comment by diamont1001** [comment]
不好意思 `require `返回的只是资源ID而不是资源对象，不能这么调用。

**Comment by staceypyee** [comment]
So we can't actually use a local photo as fallback image? @ascoders

**Comment by luojiong** [comment]
Has the problem been solved? I also have this problem
