### ISSUE TITLE
加载本地图片失败

### ISSUE THREAD

**Issue by Thyiad** [ascoders/react-native-image-viewer#36]
我使用本地图片加载时报错（安卓，格式为file:///sdcard/xxx.jpg）

跟踪调试时发现是因为没有判断是否为本地文件，统一调用了Image.prefetch：
`const prefetchImagePromise = Image.prefetch(image.url)`
能否在这里加个判断呢，如果是本地文件就success（或者判断文件存在再success）

PS：因为typescript还没用过，也不知道该怎么重新编译，束手无措。。

**Comment by Thyiad** [comment]
只能把你编译好的js拷贝出来，修改了一下，判断不是http开头，就 imageLoaded = true; 

要是能有空指点一下怎么搭建ts环境就更好了。。

**Comment by ascoders** [comment]
2.0.3 版本修复了，顺便 `readme` 添加了如何编译：`npm install && npm run tsc`
