### ISSUE TITLE
【建议】不通过`imageUrls`传递数据，而是通过`props.children`自动获取数据

### ISSUE THREAD

**Issue by 15669028801** [ascoders/react-native-image-viewer#364]
例如
```
<ImageViewer >
   <ImageItem url="****" />
  <ImageItem url="****" />
  <ImageItem url="****" />
</ImageViewer [>](url

)
```

通过React.Children.map 对ImageItem 进行改造，通过遍历出props 自动获取 imageUrls

![1572916024](https://user-images.githubusercontent.com/35586321/68170663-af79db00-ffab-11e9-8081-3e4382c65858.jpg)

**Comment by ascoders** [comment]
好像没有实质性好处，功能等价。
