### ISSUE TITLE
Please publish v2.2.27. I want maxScale

### ISSUE THREAD

**Issue by nitaking** [ascoders/react-native-image-viewer#366]
please published.
I want this: https://github.com/ascoders/react-native-image-viewer/commit/6be276ea11c35f8c2f6058edf4e6db704c9eb18d

**Comment by nitaking** [comment]
I can't help doing this:
###### package.json
```
{
  "dependencies": {
   ...
  "react-native-image-zoom-viewer": "git+https://github.com/ascoders/react-native-image-viewer#master",
   ...
  }
}
```

**Comment by ksetrin** [comment]
+1 
Please, update npm

**Comment by ascoders** [comment]
2.2.27 published.
