### ISSUE TITLE
option to not show the "index/total" header

### ISSUE THREAD

**Issue by oferRounds** [ascoders/react-native-image-viewer#376]
Thank you for this awesome library!

Small question: is there an option to not show the "index/total" header?

Thank you!

**Comment by probablyup** [comment]
@oferRounds try using `renderIndicator={() => null}`

**Comment by oferRounds** [comment]
@probablyup awesome, works great, thank you!!!

**Comment by Maoravitan** [comment]
renderIndicator={() => null} and also renderIndicator={() => {}} works however i am getting a typeScript error:
![image](https://user-images.githubusercontent.com/46298560/96570303-dde2ea00-12d2-11eb-8178-baee477e8edb.png)

how can i fix it?
