### ISSUE TITLE
react dependency warn

### ISSUE THREAD

**Issue by JoshYuJump** [ascoders/react-native-image-viewer#38]
After update to `react native 0.43.3`

There is a warn:

<pre>npm WARN react-native-image-zoom-viewer@1.2.47 
requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.</pre>

**Comment by ascoders** [comment]
fixed in `2.0.2`: https://github.com/ascoders/react-native-image-viewer/blob/master/package.json#L21
