### ISSUE TITLE
RN 0.60 Image not showing, only show the black background

### ISSUE THREAD

**Issue by XELoh** [ascoders/react-native-image-viewer#382]
<img width="307" alt="Screenshot 2020-03-11 at 4 44 29 PM" src="https://user-images.githubusercontent.com/16030959/76398290-964cc500-63b7-11ea-8de7-ff28ba2a75c0.png">

Exist on android and ios phone

Can someone give a solution, thanks

**Comment by XELoh** [comment]
`<ImageViewer
            imageUrls={[
              {
                uri:
                  "https://avatars2.githubusercontent.com/u/7970947?v=3&s=460",
                width: 400,
                height: 400
              },
              {
                uri:
                  "https://avatars2.githubusercontent.com/u/7970947?v=3&s=460",
                width: 400,
                height: 400
              }
            ]}
          />`

This is my code

**Comment by XELoh** [comment]
I found the solution

use renderImage to display the image

**Comment by arifinoid** [comment]
> I found the solution
> 
> use renderImage to display the image

How do you use renderImage?? can you explain to me just little bit

**Comment by devanshsadhotra25** [comment]
> I found the solution
> 
> use renderImage to display the image

can u please quote an example, how did u achieve this?

**Comment by sam9010** [comment]
@devanshsadhotra25 @XELoh 
can you example for me?

**Comment by sam9010** [comment]
it is a sample code...

 `<ImageViewer
                            index={this.state.imageViewerIndex}
                            imageUrls={this.state.imageDownload1}
                            enablePreload={true}
                            renderHeader={() => (
                                <TouchableOpacity
                                    onPress={() => this.setState({ isShowImageZoom : false })}
                                    style={{ alignItem: 'right',backgroundColor:'#1111' }}
                                >
                                    <Text style={{ color: '#F7F7FA', fontSize: 15, fontFamily: 'font' }}>X</Text>
                                </TouchableOpacity>
                            )}

                            loadingRender={() => (
                                <ActivityIndicator
                                    color={'#FFA800'}
                                    size="large"
                                    style={{
                                        height: Dimensions.get('window').height,
                                        alignItems: 'center',
                                        justifyContent: 'center',
                                    }}
                                />
                            )}
                            renderImage={(props) => (
                                <Image
                                style={{
                                width: 400,
                                height: 400,
                                alignItems: 'center',
                                alignContent: 'center',
                                justifyContent: 'center',
                            }}
                                resizeMode="contain"
                                source={{uri: `data:image/gif;base64,${this.state.imageDownload}`}}
                                />
                            )}
                        />`

**Comment by sjonchhe** [comment]
have you passed height width white creating this array this.state.imageDownload1 ??
