### ISSUE TITLE
Warning regarding useNativeDriver when displaying ImageViewer

### ISSUE THREAD

**Issue by gramosl** [ascoders/react-native-image-viewer#388]
I'm using React Native 0.62 and when I display a ImageViewer it thows me various warnings regarding useNativeDriver:
![Screenshot from 2020-04-10 11-23-26](https://user-images.githubusercontent.com/7204964/78984278-29e3f380-7b26-11ea-917a-fa347c57a5c8.png)
Does anyone knows why?
Thanks in advance

**Comment by EhsanSarshar** [comment]
I have the same problem

**Comment by ducpt2** [comment]
+1 i had the same issue.

**Comment by flutterhope** [comment]
node_modules/src/image-viewer.component.tsx
node_modules/built/image-viewer.component.js

find Animated.timing

add useNativeDriver: false
