### ISSUE TITLE
似乎不支持本地文件

### ISSUE THREAD

**Issue by shoutleafy** [ascoders/react-native-image-viewer#39]
如题，尝试传入本地文件提示：Failed prop type: Invalid prop `source` supplied to `Image`

**Comment by max-mykhailenko** [comment]
I have same issue. How we can fix that?

**Comment by max-mykhailenko** [comment]
PS. Please, write in english )

**Comment by max-mykhailenko** [comment]
It happens when you pass incorrect url. Recheck url

**Comment by Thyiad** [comment]
我手动改了一下解决了。。

https://github.com/ascoders/react-native-image-viewer/issues/36

**Comment by ascoders** [comment]
please try 2.0.3, thx @Thyiad
