### ISSUE TITLE
Support Android ?

### ISSUE THREAD

**Issue by ifzm** [ascoders/react-native-image-viewer#4]
按示例写的Demo无法显示图片

**Comment by ascoders** [comment]
正在适配安卓，简书也有人提了 bug，会尽快修复

**Comment by ascoders** [comment]
已兼容安卓，是默认 overflow:hidden 的问题

**Comment by ascoders** [comment]
1.2.14

**Comment by ifzm** [comment]
更新了npm包，依旧不能显示图片，Android 6.0

**Comment by ascoders** [comment]
是第一张图能显示，之后的就无法显示吗

**Comment by ifzm** [comment]
不是，就是没有任何内容，model内是空白

**Comment by ifzm** [comment]
Modal

**Comment by ascoders** [comment]
别人都跟我说安卓没问题了，你仔细看一下版本号是多少？

**Comment by ifzm** [comment]
最新的1.2.18

**Comment by ascoders** [comment]
实测没问题，很可能是用法有问题。贴代码吧。

**Comment by ifzm** [comment]
晚上回去我写个单独的示例页面再看看

**Comment by ifzm** [comment]
![image](https://cloud.githubusercontent.com/assets/12740295/18874972/83a51ed2-84f6-11e6-9ea7-d909424e0d11.png)
![image](https://cloud.githubusercontent.com/assets/12740295/18875012/9c3a89aa-84f6-11e6-8313-f95de193b1b3.png)

**Comment by ifzm** [comment]
我新开了个页面，依旧不能显示...  原因不明

**Comment by ifzm** [comment]
刚发，就发现了，是示例不对，没注意看API，需要设置 visible={true}

**Comment by ifzm** [comment]
建议更新一下readme,也许也有人遇到这个问题,毕竟是好东西  )

**Comment by ascoders** [comment]
是示例有问题，已更新 readme。
