### ISSUE TITLE
OnLayout bug

### ISSUE THREAD

**Issue by max-mykhailenko** [ascoders/react-native-image-viewer#41]
After changing orientation my images still shows not aligned to center
![screen shot 2017-04-24 at 11 24 39 am](https://cloud.githubusercontent.com/assets/1213198/25328454/9deeefc8-28e0-11e7-8978-30673ea5581a.png)

After several swipes my images concating to one screen.
![screen shot 2017-04-24 at 11 27 03 am](https://cloud.githubusercontent.com/assets/1213198/25328551/f3d5c5d8-28e0-11e7-9ae1-333e921c21b9.png)

**Comment by hasancanozkan** [comment]
I have the same problem.. any solutions for it??

**Comment by ascoders** [comment]
Maybe you can use [react-native-orientation](https://github.com/yamill/react-native-orientation) 
listening the screen direction's change. Then forceUpdate will be help: https://github.com/ascoders/react-native-image-viewer/blob/master/src/image-viewer.component.tsx#L364.

**Comment by max-mykhailenko** [comment]
@hasancanozkan I decide to remove `react-native-image-viewer` and write own pagination

**Comment by ascoders** [comment]
It's fine too.
