### ISSUE TITLE
Hide StatusBar on model show.

### ISSUE THREAD

**Issue by Ace000001** [ascoders/react-native-image-viewer#410]
I was wondering if there is a way to hide the statusbar when viewer is visible? I can set the background and color of status bar but i reduces the focus while browsing images.

**Comment by reyn-nova** [comment]
import { StatusBar } from 'react-native'

StatusBar.setHidden(true) //before set visible true?

then on Modal onDismiss set the status bar hidden false again

**Comment by Ace000001** [comment]
@rp-nova Thanks for your reply. Already tried that. But when i hide the StatusBar on the model my StatusBar on the parent screen gets visible behind the model. I even tried setting the zIndex of the model but no use. Model is not taking the space of full screen leaving the safe area on top.

**Comment by rp-nova** [comment]
@Ace000001  or you can just set it translucent and set the statusbar background to 'transparent'

**Comment by reyn-nova** [comment]
@Ace000001  could you tell me, if you set the status bar translucent to true followed by changing status bar background to 'transparent', does it also not working?

**Comment by reyn-nova** [comment]
just only when the viewer is visible, after that you can return it back to the previous status bar state

**Comment by Ace000001** [comment]
I wasn't working even with translucent true and transparent background. Due to the shortage of time I switched to an other plugin and it had an built in option to hide the status bar for full screen view. So i got it working with another package.

**Comment by suhailamir** [comment]
@Ace000001 Could you tell what other package you used, Thanks.

**Comment by Ace000001** [comment]
@suhailamir [Here](https://www.npmjs.com/package/react-native-image-viewing)

**Comment by suhailamir** [comment]
Thanks @Ace000001
