### ISSUE TITLE
Footer not centering

### ISSUE THREAD

**Issue by kockok** [ascoders/react-native-image-viewer#420]
I added
```
    justifyContent: 'center',
    alignSelf: 'center',
    alignContent: 'center',
    alignItems: 'center',
```
in both the `<View>` and <Text>` components.

However, the `<Text>` component just won't center.

![Screenshot 2020-08-09 at 6 04 17 PM](https://user-images.githubusercontent.com/232541/89729693-ce415c80-da6a-11ea-9716-32feabd4224e.png)

**Comment by kockok** [comment]
> => (<ImageFooter/>)}
>     footerContainerStyle=

Not working

**Comment by ntodd** [comment]
```
footerContainerStyle={{ width: "100%", flexDirection: "row", justifyContent: "center" }}
```

**Comment by Nayan014** [comment]
` footerContainerStyle={{ alignItems: 'center', right: 0, left: 0, bottom: 14 }}`
