### ISSUE TITLE
No Option to hide page number indicator 

### ISSUE THREAD

**Issue by eramudeep** [ascoders/react-native-image-viewer#439]
No option found the hide the Page number, Kindly help if anyone knows 
<img width="357" alt="Screenshot 2020-12-01 at 5 07 23 PM" src="https://user-images.githubusercontent.com/38516686/100735856-e95c2180-33f7-11eb-93ad-fa0f04ec82b1.png">

**Comment by jaaywags** [comment]
Add this
`<ImageViewer
 ...
 renderIndicator={() => <></>} />`

See #191 or #408

**Comment by eramudeep** [comment]
Thanks for the reply. Let me figure it out.

**Comment by eramudeep** [comment]
Yo worked for me !!!!!  🥳 🥳 🥳 🥳 🥳 🥳 🥳 🥳
