### ISSUE TITLE
图片变模糊了

### ISSUE THREAD

**Issue by 1610449813** [ascoders/react-native-image-viewer#44]
使用imageviewer后打开图片，感觉图片变模糊了，求解？

**Comment by 1610449813** [comment]
我看了源码，里面查看原图怎么触发这个方法啊

**Comment by ascoders** [comment]
那个方法适用于传入一个缩略图，一个原图，如果你把原图当作缩略图传入，显示的就是原图。变模糊是真机还是模拟机呢？我测试真机上没有变模糊呀

**Comment by 1610449813** [comment]
真机，我是把原图传入的
 Image.getSize(image.uri, (width, height) => {
                        zoom.push({ url: image.uri, width: width, height: height });
                    }, (error) => {
                    })然后把zoom放入到imageviewer里面的，和手机相册里面的图片对比，明显变模糊了

**Comment by 1610449813** [comment]
不好意思，不是viewer的问题，是这个react-native-image-picker设置的问题

**Comment by JasonLeeSen** [comment]
查看原图貌似没有什么用啊，orginUrl也没有用

**Comment by tianweicc** [comment]
@ascoders 长图打开的话 糊了 有解决方法么

**Comment by hu-qi** [comment]
@ascoders tianweicc  请问长图打开的话 糊了 有解决方法么
