### ISSUE TITLE
failImageSource 图片显示不正常

### ISSUE THREAD

**Issue by dongodngtang** [ascoders/react-native-image-viewer#47]
图片加载失败，failImage 显示在右下角，而且很小

**Comment by zmGitHub** [comment]
同样的问题, 这个不能自己配置吗?            failImageSource={{ uri: 'https://gss0.baidu.com/9vo3dSag_xI4khGko9WTAnF6hhy/zhidao/wh%3D600%2C800/sign=4c1580d505087bf47db95fefc2e37b14/aa18972bd40735fab74df12799510fb30e2408ea.jpg' }}

**Comment by hyp-Zero** [comment]
failImage设置的图片并没有显示。可以改成方法吗

**Comment by ascoders** [comment]
```javascript
<ImageViewer
  imageUrls={images}
  failImageSource={{
    url: "https://avatars2.githubusercontent.com/u/7970947?v=3&s=460",
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").width
  }}
/>
```

Effective in version `2.0.18`.
