### ISSUE TITLE
Local images

### ISSUE THREAD

**Issue by ahirag** [ascoders/react-native-image-viewer#48]
Hi,
Great library!
I have noticed a new update to support local image and I am trying to use it.
Tried with the 'file:' + sourcePath but didn't manage to make it work.

Tried to do this:
const images = [{
  url: 'file:../images/IMG.JPG'
}]

Is it possible ? 
Thanks,

Ahikam

**Comment by ascoders** [comment]
I don't have an environmental test right now, can you please try to debug this code: https://github.com/ascoders/react-native-image-viewer/blob/master/src/image-viewer.component.tsx#L148 ?
If it is startWith `file:`, it will set to load success.

**Comment by ahirag** [comment]
Thats what we tried to do, used this file: from your last update.
Didn't manage to load the image on iPhone/Android.

**Comment by LEEY19** [comment]
@ahirag have you been able to display local images smoothly?

**Comment by ascoders** [comment]
fix in version: `2.0.9`
