### ISSUE TITLE
Zooming does not load full resolution image

### ISSUE THREAD

**Issue by markdaws** [ascoders/react-native-image-viewer#54]
If I have a large resolution image, when I zoom in the image just seems to be scaled up rather than being able to zoom all the way in to the image, I end up with just seeing a blurry image.

Does this component support zooming and letting the user see the higher resolution version of the image as they zoom, vs. just scaling the image from some reduced size?

**Comment by ascoders** [comment]
@markdaws, thank you for your advice, but this library does not support this usage.I think there are more suitable for other professional base, such as map plug-in, update a larger resolution at each zoom diagram after reduce size, and only show one big picture, no carousel.

**Comment by markdaws** [comment]
@ascoders - thanks for the reply. How does the viewer resize the original image?  Lets say I have an image that is 3000x2000 pixels and open it on an iphone with this viewer, is the image scaled down to something like 1500x1000 for example so that is the max I can zoom?  The images I have aren't very big, but just trying to figure out if I can use this component to view them.

**Comment by ascoders** [comment]
@markdaws [Here](https://github.com/ascoders/react-native-image-zoom/blob/master/image-zoom/image-zoom.component.tsx#L441) use `transform .scale` to resize original image.
