### ISSUE TITLE
图片放大后，android的虚拟返回键没法监听。

### ISSUE THREAD

**Issue by aijason** [ascoders/react-native-image-viewer#55]
图片放大后，android的虚拟返回键没法监听。点击返回处理图片变小没法实现

**Comment by ascoders** [comment]
虚拟键盘的监听似乎与放大缩小没啥关系吧

**Comment by Anluis** [comment]
@aijason 
https://facebook.github.io/react-native/docs/modal.html
Use onRequestClose

**Comment by ascoders** [comment]
Thanks @Anluis , and i will close this issue.
