### ISSUE TITLE
自定义头部 怎么弄呢？

### ISSUE THREAD

**Issue by wunayou** [ascoders/react-native-image-viewer#56]
我需要一个 顶部显示  返回  一个标题   一个删除按钮   所以就是一个navigate 就可以解决

但是你把我的。。。。看不见了

**Comment by ascoders** [comment]
是 `1/3` 这个文字把自定义头部内容挡住了吗？

**Comment by wunayou** [comment]
我的需求是这样的  跟微信朋友圈发布一样 
![_20170703145921](https://user-images.githubusercontent.com/25662123/27781406-4c089ff4-6000-11e7-9296-2c2c2429dc97.jpg)

标题 显示 1/3这种

**Comment by wunayou** [comment]
是不是model 影响的 还是？

**Comment by ascoders** [comment]
肯定是 Model 盖住了，换个容器吧

**Comment by wunayou** [comment]
但是奇怪了 我换了view 也是一样的

**Comment by ascoders** [comment]
但是组件也仅使用了 View：https://github.com/ascoders/react-native-image-viewer/blob/master/src/image-viewer.component.tsx#L559

**Comment by ascoders** [comment]
没有进展，暂时先关闭

**Comment by Fanstay** [comment]
请问你的问题解决了吗，我也做到这个功能了。。
