### ISSUE TITLE
can't display image chose from photo gallery for Android

### ISSUE THREAD

**Issue by normanzhang1980** [ascoders/react-native-image-viewer#7]
This functionary is work well for IOS, but Android doesn't.
The relative code as below:
==============================
            if (Platform.OS === 'ios') {
               source = {uri: response.uri.replace('file://', ''), isStatic: true};
            } else {
               source = {uri: response.uri, isStatic: true};
            }
==============================

**Comment by ascoders** [comment]
Code similar to the following ?

```typescript
<ImageViewer visible={true} imageUrls={[{url: source}]}/>
```

Can you let me see error screenshot?

This is how i use source: https://github.com/ascoders/react-native-image-viewer/blob/master/image-viewer/image-viewer.component.tsx#L297

**Comment by normanzhang1980** [comment]
yes. Code is similar. 

var imagesArr;
export default class BigImage extends Component {
  componentWillMount(){
    imagesArr = Array();
    for(var i = 0; i < this.props.selectImgUrlArr.length; i++) {
      imagesArr.push({url: this.props.selectImgUrlArr[i]});
    }
  }
  render() {
    return (
      <View style = {styles.content}>
        <NavHeader
          nav = {this.props.nav}
          title = {"图片查看"}
        />
      <View style = {{flex: 1}}>
        <ImageViewer visible = {true} imageUrls = {imagesArr} index = {this.props.selIndex}/>
      </View>
      </View>
    )
  }
}
By the way: it work well if the image come from web for Android.

**Comment by ascoders** [comment]
Have you solved the problem?
