### ISSUE TITLE
renderFooter example

### ISSUE THREAD

**Issue by sood03** [ascoders/react-native-image-viewer#70]
I have my ImageViewer as 

```
                     <ImageViewer
                            imageUrls={fullImagesURLs}
                            index={this.state.curIndex}
                            renderFooter = { () => {
                                return <Text>FooterText</Text>
                            }}
                        />
```

But this Footer Text is not visible in full screen mode. I referred to [#51](https://github.com/ascoders/react-native-image-viewer/issues/51)  but can't figure out what's wrong in above example.

**Comment by umaulana** [comment]
got same issue

**Comment by zygama** [comment]
I can't make it work too.. that's too bad because i can't close the modal on iOS :/

**Comment by jiyeon-dino** [comment]
Is the problem solved?

**Comment by Dror-Bar** [comment]
Hi, I have the same issue. Why was this closed? is there a working example?

**Comment by micheilsgrey** [comment]
> Here is an example:
> 
> ```
> 
> _renderFooter() {
>   return (
>     <View style={{ height: 100, backgroundColor: 'red' }}>
>          <Text style={{ fontSize: 16, color: 'white', textAlign: 'center' }}>Footer</Text>
>      </View>
>   );
> }
> 
> 
> <ImageViewer
>          imageUrls={fullImagesURLs}
>          index={this.state.curIndex}
>          footerContainerStyle={{ width: '100%' }}
>          renderFooter = {this._renderFooter}
>            />
> ```

Why footer rendering behind the screen, with height of 50 I simply do not see my footer. Only after over 50 height I start to notice my footer.
