### ISSUE TITLE
双击放大,真机下会出现不放大,会偏移的效果,模拟器没问题

### ISSUE THREAD

**Issue by CoderZF** [ascoders/react-native-image-viewer#72]

**Comment by CoderZF** [comment]
希望能抽空看看这个问题哦,还有为什么我修改源码之后 为啥没办法编译到项目中去啊

**Comment by ascoders** [comment]
可以进入 `node_modules/react-native-image-viewer` 执行 `tsc -w`，项目刷新就生效了。

**Comment by CoderZF** [comment]
找不到 tsc这个命令啊  如何安装的?typeScript  没用过 @ascoders

**Comment by ascoders** [comment]
用的是 npm5 吗？可以执行 `npx tsc -w`，或者 `npm install typescript -g` 再执行 `tsc`

**Comment by CoderZF** [comment]
Node 6.11 npm是3.10.10  我试试。。谢谢




发自网易邮箱大师
在2017年08月23日 16:49，黄子毅 写道：

用的是 npm5 吗？可以执行 npx tsc -w，或者 npm install typescript -g 再执行 tsc

**Comment by lhyzxc** [comment]
双击放大确实不太好用，很多时候双击后图片发生偏移。怎么解决啊？？

**Comment by vipstone** [comment]
目前测试了android真机，问题2个：
1.有时候双击图片发生偏移，也没放大；
2.有时候双击，图片变大了（几率很小），没有居中，图片顶到最上面或者最下面了；

请求及时修复。

**Comment by 369663841** [comment]
@vipstone @ascoders 
vipstone反馈的问题我也遇到了，测试了若干android手机，对于双击放大，是有的可以，有的无效。尝试了很久，发现如果将：
                        Animated.parallel([
                            Animated.timing(this.animatedScale, {
                                toValue: this.scale,
                                duration: 100,
                            }),
                            Animated.timing(this.animatedPositionX, {
                                toValue: this.positionX,
                                duration: 100,
                            }),
                            Animated.timing(this.animatedPositionY, {
                                toValue: this.positionY,
                                duration: 100,
                            })
                        ]).start()
三个分开来单独执行，双击放大就都有效了，具体原因不清楚。

在测试中还发现两个问题（android和iOS下都存在）：
1、图片会发生偏移（在双击放大/还原，以及图片切换操作时，常会发生）
2、即使不放大图片，当从一个小的图（高度较小），切换到一个较高的图（纵向），然后又切回到之前较小的图时，小图会自动放大了，并且发生偏移。

为了解决这两个问题，我考虑想舍弃一些效果，当图片切换时，就将图片回复初始状态，但怎么试都不得其法，比如我想在 viewer 的 goBack 和 goNext 方法里去调 zoom 的 reset方法，但无法取得zoom的ref。请教@ascoders，我这样考虑是否走得通，还是能有别的办法让图片在切换时回复初始状态？谢谢！

**Comment by ascoders** [comment]
@369663841 第一个问题看上去是 RN 自身的 bug，看能不能通过升级 RN 版本解决？

另外 reset 的问题 #101 讨论的也很火热，我这周应该会花时间修复下。另外如果有好的解决方案，欢迎提交 PR。

**Comment by 369663841** [comment]
@ascoders 非常感谢！

**Comment by kokiy** [comment]
@ascoders  thanks

**Comment by ascoders** [comment]
Fixed in `2.0.16`. 这个 bug 原因是真机双击可能被认为触发了移动，已修复。
