### ISSUE TITLE
建议修改下handleLongPress函数做成回调函数，长按不一定仅仅只有保存到相册哇

### ISSUE THREAD

**Issue by cloudsafe** [ascoders/react-native-image-viewer#73]
建议修改下handleLongPress函数做成回调函数，长按不一定仅仅只有保存到相册哇
我先自己改了，另外加了点上下滑动退出。

**Comment by ascoders** [comment]
`2.0.10` 版本增加了 `onLongPress` 的 `props`。
如果 `saveToLocalByLongPress` 是 false，就不会出现调用相册。

**Comment by cloudsafe** [comment]
我咋没看到10版本？

**Comment by cloudsafe** [comment]
额，2分钟前。。。
