### ISSUE TITLE
ios模拟器保存到相册报错

### ISSUE THREAD

**Issue by zoenleo** [ascoders/react-native-image-viewer#75]
Cannot read property 'saveToCameraRoll' of undefined

**Comment by LZhong3196** [comment]
模拟环境为iphone 6 - ios 10.1

**Comment by luzhaung** [comment]
@LZhong3196 看这里，哥们。[https://www.shiqidu.com/p/132](url)

**Comment by Geek-ch** [comment]
iOS需要导入CameraRoll组件

**Comment by ascoders** [comment]
看来问题已得到解决。
