### ISSUE TITLE
Build errors with TypeScript 2.4.2

### ISSUE THREAD

**Issue by ouss-athome** [ascoders/react-native-image-viewer#77]
When using TS 2.4.2 the project is not working anymore. This is because of this type of error:
```
node_modules/react-native-image-zoom-viewer/src/image-viewer.component.tsx(414,32): error TS2322: Type '{ style: ImageStyle[]; source: { uri: string; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ImageProperties, ComponentState>> & Read...'.
  Type '{ style: ImageStyle[]; source: { uri: string; }; }' is not assignable to type 'Readonly<ImageProperties>'.
    Types of property 'style' are incompatible.
      Type 'ImageStyle[]' has no properties in common with type 'ImageStyle'.
```
This because appending two styles in an array does not work with newer versions of typescript. 

For example, this does not work:
`<Image style={[this.styles.imageStyle, { width: width, height: height }]} />`
But this works:
`<Image style={Object.assign({}, this.styles.imageStyle, { width: width, height: height })} />`

**Comment by ou2s** [comment]
I made a pull request to solve the issue: https://github.com/ascoders/react-native-image-viewer/pull/78
