### ISSUE TITLE
如何实现双击退出大图浏览?

### ISSUE THREAD

**Issue by yuanji123** [ascoders/react-native-image-viewer#8]
比如我想实现在大图部分实现双击 退出大图浏览，如何实现，可以提供一个双击的回调么

**Comment by ascoders** [comment]
其实双击应该是放大图片

**Comment by yuanji123** [comment]
@ascoders  比如电商商品详情页，是点击图片，会进入大图浏览，然后再双击会退出大图浏览。但是你的实现好像是双击出现保存相册，保存相册这个也不是必要功能，应该提供接口屏蔽下~

**Comment by ascoders** [comment]
已新增

**Comment by ascoders** [comment]
已新增 onClick onDoubleClick 接口，可以自己控制取消的时机。
新增 saveToLocalByLongPress 参数控制长按是否开启保存相册功能。

v1.1.9

**Comment by yuanji123** [comment]
@ascoders  thank
