### ISSUE TITLE
预览图是永远是正方形，版本是2.0.9

### ISSUE THREAD

**Issue by VanStranger** [ascoders/react-native-image-viewer#80]
drawable目录里的图片，比较宽的图会显示成正方形，比较高的还没有试，这种图片的宽高要自己设置吗？

**Comment by ascoders** [comment]
缩放处理逻辑是：图片宽度超过屏幕宽度，整体缩放至图宽与屏宽相等；高度超过了也一样缩放；两者同时缩放则缩放到最后一边在屏幕内为止。
