### ISSUE TITLE
双击时间间隔太小。怎么破？

### ISSUE THREAD

**Issue by cloudsafe** [ascoders/react-native-image-viewer#86]

**Comment by cloudsafe** [comment]
在调用imageZoom增加参数，，

**Comment by 369663841** [comment]
@cloudsafe 请问是通过设置leaveStayTime参数吗？我现在的问题是 增加了 onClick处理（关闭imageViewer）后，默认的onDoubleClick放大 效果就无效了，请指点一下，谢谢！
