### ISSUE TITLE
imageUrls 用什么格式数据？

### ISSUE THREAD

**Issue by kidolee** [ascoders/react-native-image-viewer#88]
const imageUrls=[{url:'https://dev.merlincrm.com/bec/api/bex/product/image/76'},
  {url: 'https://dev.merlincrm.com/bec/api/bex/product/image/77'},
  {url: 'https://dev.merlincrm.com/bec/api/bex/product/image/78'}]

这样的就可以吗

          <ImageViewer
              imageUrls={imageUrls}
              enableImageZoom={true} 
              index={1} 
              failImageSource={Icon1}
              onChange={(index) => {}}
              onClick={() => {}}
          />
这样写就行吗？

**Comment by ascoders** [comment]
对的。
