### ISSUE TITLE
报错undefined is not an object (evaluaing "image.url.startsWith")

### ISSUE THREAD

**Issue by msevensun** [ascoders/react-native-image-viewer#89]
const images = [{
    url: '0.jpg'
}, {
    url: '1.jpg'
}, {
    url: '2.jpg'
}]
这种格式可以。如果换成
  const images = [ '0.jpg','1.jpg', '2.jpg']  就会报错undefined is not an object (evaluaing "image.url.startsWith")，如何修改数据格式？

**Comment by ascoders** [comment]
在代码中预处理一下格式，转成组件需要的格式再传入。
