### ISSUE TITLE
安卓打开之后一直闪

### ISSUE THREAD

**Issue by as27543035** [ascoders/react-native-image-viewer#9]

**Comment by ascoders** [comment]
提供一下使用方法，还有不太清楚一直闪是什么意思

**Comment by as27543035** [comment]
用的就是你提供的例子，一直闪好像是界面一直在不断刷新。（RN版本是0.33.0）

**Comment by ascoders** [comment]
原因是安卓子元素变化也会不断触发 `onLayout`，迫使我没法好好动态计算宽高，不过现在通过 tag 解决了，升级到 `v1.2.26`
