### ISSUE TITLE
单击跟双击事件冲突啊

### ISSUE THREAD

**Issue by jeffy7** [ascoders/react-native-image-viewer#91]
实现了onClick后，双击事件 默认放大被拦截啊，麻烦问一下怎么解决

**Comment by jeffy7** [comment]
我实现的是单击让看大图消失

**Comment by 369663841** [comment]
@jeffy7 兄台，我跟你是一样的需求一样的问题，请问你现在解决了吗？

**Comment by ascoders** [comment]
最新版好像解决这个问题了，我最近合了一个 pr。https://github.com/ascoders/react-native-image-zoom/pull/27

**Comment by 369663841** [comment]
@ascoders 感谢！更新到 2.0.12 ，解决了这个问题。

**Comment by 369663841** [comment]
@ascoders 您好！在真机测试中，我左手拿手机，如果用右手食指去操作，不论单击（关闭）或双击（放大/取消放大），效果都很好；但如果用左手拇指去操作，单击没反应，双击变成了关闭（单击的效果）。是因为拇指接触屏幕的面积大，还是因为双击速度不够快呢？该如何解决， 敬请指点！谢谢！

**Comment by ascoders** [comment]
双击变成单击效果，可能由于双击速度不够快。单击必须在很小的位移范围内抬起才会触发，如果按下去后移动了比较大一段距离，再抬起来，就当作没有触发单击。

**Comment by jeffy7** [comment]
@ascoders 我发现了一个bug，在图片没下载下来的时候，滑动，会崩溃在，
- (void)URLRequest:(id)requestToken didReceiveData:(NSData *)data
{
  if (![self validateRequestToken:requestToken]) {
    return;
  }

  if (!_data) {
    _data = [NSMutableData new];
  }
  [_data appendData:data];

appendData 这里，应该是图片下载的问题，我本来就不想用<Image>组件，于是我在
loadImage(index) {}
强制返回了成功，图片下载我交给native的SD去做，
