### ISSUE TITLE
当图片达到两百以上时 app会崩溃

### ISSUE THREAD

**Issue by zslzz** [ascoders/react-native-image-viewer#96]
道友最好做一下优化处理   不要把所有的图片资源都渲染

**Comment by zslzz** [comment]
哈哈哈 我找到了解决方案

**Comment by ascoders** [comment]
怎么解决的？

**Comment by zslzz** [comment]
把这个组件重新加载一次就行 
简单粗暴

**Comment by zslzz** [comment]
道友 该项目新版本 的图片在缓存时 会失真    建议增添是否缓存选项

**Comment by shiyunsheng** [comment]
组件重新加载一次是啥意思？

**Comment by zslzz** [comment]
this.setState();

**Comment by CoderSwitch** [comment]
如何this.setState();能否具体一些呢，我也遇到加载过多图片会内存崩溃的问题了，方便的话最好给与一些代码

**Comment by zslzz** [comment]
@CoderSwitch  看一下reactnative的生命周期吧。
