### ISSUE TITLE
图片加载时不能左右滑动

### ISSUE THREAD

**Issue by JackieQu** [ascoders/react-native-image-viewer#99]
ExceptionsManager.js:71 Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the ImageViewer component.

大图加载时候，左滑右滑没反应，会直接消失，这个应该在哪里修改一下呢

**Comment by ascoders** [comment]
fixed in `2.0.16`.
